### ISSUE TITLE
Strukturert gjennomgang av krav til UU og WCAG 

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#10]
CI/GH Action for a11y validation. Consider using the [`tesk9/accessible-html`](https://package.elm-lang.org/packages/tesk9/accessible-html/latest/) package instead of `elm/html`.

**Comment by tormoseng** [comment]
Funskjonell gjennomgang ligger her: https://teams.microsoft.com/_?tenantId=339927f0-7da5-4b36-979e-eb40c1d4b035#/xlsx/viewer/recent/https:~2F~2Fatbno.sharepoint.com~2Fsites~2FAtBeta~2FDelte%2520dokumenter~2FGeneral~2FUniversell%2520utforming~2FWCAG%25202.0%2520-%2520AtB%2520nettbutikk.xlsx?baseUrl=https:~2F~2Fatbno.sharepoint.com~2Fsites~2FAtBeta&fileId=e7d2c5f9-f4f5-4eb4-8731-07a295662bf1&ctx=recent&viewerAction=view

Merk at denne tabellen må gås gjennom for å se på hva som må gjøres og hva som er nice-to-have. Det er også mulig at observasjonene er plassert på feil forskriftsnummer pga undertegnedes manglende erfaring på UU-testing.

**Comment by tormoseng** [comment]
En gjennomgang av sidene med WAVE-extension for Chrome gir følgende feil/advarsler:

** Innlogging **
- ERR: manglende alternativ tekst for bildet

** Oversikt **
- ADV: Skippet heading-level fra h1 til h3

** Kjøp billett **
- ERR: Manglende form-label på sone og tid (men dette rettes vel opp i annen sak)
- ADV: "Kjøp billett" får underline (dette er vel dog veldig bevisst)
- ADV: Manglende select-label på sone og tid (som ERR over)

** Kjøpshistorikk **
- ADV: Som for "Kjøp billett" over

** Min profil **
- ADV: Som for "Kjøp billett" over

**Comment by mikaelbr** [comment]
> ERR: manglende alternativ tekst for bildet

Dette er med hensikt da det kun er illustrativt og ikke trengs å bli lest opp. Men kan markere bildet som role=none

**Comment by mikaelbr** [comment]
> ERR: Manglende form-label på sone og tid (men dette rettes vel opp i annen sak)
> ADV: Manglende select-label på sone og tid (som ERR over)

@tormoseng Det skal være fikset nå.

**Comment by hildeor** [comment]
Gått gjennom alle krav utenom 2.1.1 Tastatur. Todo.
Er opprettet nye issues basert på funn som er gjort, alle skal være tagget med "accessibility".

**Comment by mikaelbr** [comment]
Fenomenal innsats av både @tormoseng og deg @hildeor ! Skal denne lukkes nå da eller gjenstår 2.1.1 før det gjøres?

**Comment by hildeor** [comment]
Jeg kan teste 2.1.1 i morgen håper jeg, så kanskje vente litt med å lukke så får vi bare tatt alt.

**Comment by hildeor** [comment]
2.1.1 er også testet OK.
