### ISSUE TITLE
Fjerne muligheten for å legge inn epost ved tilbakemeldinger via Intercom

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#103]
**Beskrivelse **
Ved kontakt via Intercom i dag får bruker en mulighet til å legge inn sin epost som skal varsles ved svar. Dette fungerer pr nå ikke (testet på nettbutikk i staging), samtidig som det virker til ikke å være en mulighet å svare via epost fra Intercom heller.

I tillegg er det mulig vi bør unngå å lagre epost siden Intercom driftes fra USA (Schrems II).

Se dialog om dette på Slack: https://mittatb.slack.com/archives/C01MT34KJ4B/p1619771006337800

**Reprodusering**
1. Send en mld via Intercom og se at innlegging av epost fremkommer

**Comment by tormoseng** [comment]
Saken fremkom under test av #79

**Comment by jahnrohme** [comment]
Ikke prioritert
