### ISSUE TITLE
Forbedre kjøpsflyt til å være i samme vindu uten blokkering av popup

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#107]
**Konseptuell beskrivelse og behov som skal løses**
Nå er flyten for Nets og Vipps litt rar med at den sender til helt separate sider og så til en side som deretter kan lukkes. I det dette pågår vil webshop polle etter mulig capture/payment error etc. Dette føles litt snodig for brukeren og det kan være litt sårbart for feilhåndtering med tilstand som må være korrekt spesielt i sammenheng med #105. Nå så lukker man et vindu og plutselig får opp en helt ny side i nettbutikk uten at man er med på den overgangen.

Utforsk om det er mulig å bruke Vipps og Nets i en "seamless mode" i en iframe, uten at det blir tatt ut fra eksisterende kontekst. Da vil flyten kunne være enklere ved vellykket kjøp også.

Ting å løse:

- Kunne avbryte betaling uten at det blir en evig polling etter betaling (til timeout)
- Mer sømløs feilmeldingshåndtering

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Hadde mine mistanker her, og etter litt research for både NETS og Vipps så er anbefalingen ikke iframe og heller kjøring i samme vindu. Eksempel fra Nets docs:

> When implementing a payment window, we suggest you to avoid frames including iFrames, especially if your site is not HTTPS. Instead of using frames, we strongly encourage you to use our terminal design templates that will handle any form of formatting that might be needed, making the payment window indistinguishable from any other page in your website. Frames are not recommended because:
> 
> Decrease of sales since customers might be worried to pay over unencrypted channel (phishing suspected).
Password-based 3D Secure ACS servers won’t work in a frame because of click-jack attack protection.
Reloading of the page might lose the initial transaction source URL, forcing customer to prepare an order again (for example, might be a problem when selling tickets with reserved seats).


Ikke like enkelt å finne konkret fra Vipps rundt betaling men konseptet fra login står seg uansett:

> The Vipps login API authenticates the user in the web browser. The Vipps login API should only be run in the browser window using redirects (iFrame is not supported and new window is not recommended).

De vil nok hindre bruk av iframe for å unngå lettere phising siden URL ikke er synlig. Løsningen vil være å bruke samme vindu og heller tilrettelegge bruken fra vår "SPA" (client side rendering osv)

**Comment by magnusolderoesaether** [comment]
Roger that. Hva vil dette medføre med tanke på implementasjonstid/usikkerheter?

**Comment by mikaelbr** [comment]
Litt ugunstig i løsning slik den blir nå: Ved avbrudd av Vipps/Nets vil man bli sendt tilbake fremsiden og gå inn på nytt kjøp og rekonstruere kjøp på nytt. Det kan fikses med mellomlagring, men må se på det i ettertid eventuelt.

**Comment by tormoseng** [comment]
Testet OK i staging
