### ISSUE TITLE
Bygge inn forståelse av ID-basert-konseptet ved onboarding/registrering av t:kort

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#119]
t:kort-brukere har en forståelse for at verdien av billetten er knyttet til det fysiske t:kortet. En brukertest avdekker at dette har etablert et "pattern" hvor bruker ved tap av kort ønsker å kontakte kundeservice. Gjennom å bygge forståelse for at t:kort ikke er knyttet til verdi//konto vil bruker bedre forstå hvordan egenadministrering av kort og bærere fungerer.

**Comment by magnusolderoesaether** [comment]
Har skrevet et forslag til et onboardingssteg før å prøve å rydde litt i brukerens forståelse av ID-basert og sammenheng mellom ny og gammel nettbutikk. 
![image](https://user-images.githubusercontent.com/50573205/121520709-83c69e80-c9f3-11eb-9383-6be9a4a67fa9.png)

**Comment by mjenssen** [comment]
@magnusolderoesaether Er dette klart for å implementeres nå, eller skal tekstene gjennom noen godkjenning først? Og er det bestemt hvor i flyten vi skal ha denne siden?

**Comment by tormoseng** [comment]
Testet OK i staging
