### ISSUE TITLE
La brukere legge til navn på t:kort om ønskelig

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#130]
**Konseptuell beskrivelse og behov som skal løses**
For enklere kommunikasjon i grensesnitt og mentale modeller kan det være fordelaktig for t:kort å være navngitt.

**Hypotese og foreslått løsning**
<img width="907" alt="Screenshot 2021-05-19 at 09 40 13" src="https://user-images.githubusercontent.com/606374/118774523-389eed00-b886-11eb-84fb-70c3a580749a.png">

**Annen nyttig kontekst**

Er avhengig av en modell for lagring av ekstrainformasjon tilknyttet t:kort.

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by jahnrohme** [comment]
Ikke aktuelt før vi har løst "på-vegne-av".
