### ISSUE TITLE
Sette opp mailchimpflyt fra landingsside nettbutikk 

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#152]
Onboardingskonseptet I åpen pilot medfører i hovedsak en onbaording fra https://beta.atb.no/pilotprosjekter/nettbutikk

1) Bruker legger igjen e-post i en mail-form
2) Mailchimp sender bruker info om pilot og URL til nettbutikk i prod

---

## Akseptansekriterier

- [ ] Tekst og lenker henger sammen
- [x] ~~E-post form er implementert I seksjonen "Prøv morgendagens nettbutikk i dag"~~
- [x] ~~Mailchimpflyt er satt opp testet~~
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Fixed by https://github.com/AtB-AS/atbeta/pull/39

**Comment by mikaelbr** [comment]
Denne er endret til å kun bruke informasjon og ikke gå via skjema for innsending av informasjon via mailchimp. Se ny flyt
![Screenshot 2021-05-31 at 09 49 02](https://user-images.githubusercontent.com/606374/120159377-704a5500-c1f5-11eb-9d20-758bc930f4ea.png)

**Comment by tormoseng** [comment]
Testet OK i staging
