### ISSUE TITLE
Ekstra steg i onboarding før åpen BETA: Klargjøring av muligheter/begrenseninger for bruker

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#153]
Selv om onboarding til åpen BETA primært styres gjennom kontekst på landingsside, må vi regne med at URL til nettbutikk i produksjon vil deles og at brukere vil onboardes direkte uten den konteksten. Vi trenger derfor en en initiell onboardingsblokk som beskriver muligheter og begrensninger for bruker (overordnet) samt lenke til mer informasjon på landingsside.

---

## Akseptansekriterier

- [x] Innhold er laget
- [x] Design er implementert I Figma
- [x] Onboardingssekvens er implementert som del 1 av dagens flyt. 
- [x] Fungerer i alle store evergreen nettlesere.
- [x] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
@magnusolderoesaether Denne er ferdig?
