### ISSUE TITLE
Forbedre presentasjon av gyldig billett i nettbutikk

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#155]
Brukertestene viser at visning av gyldig billett er forvirrende. Gjennom forbedring av tekst og potensielt animasjon må vi tydeliggjøre hva som er billett, hva som er billettbærer, hva som er kvittering, og hva som skal benyttes i ulike kontekster

1) Fobedre copy
2) Vurdere iterasjon av design
3) Tydeliggjøre i onboarding

**Annen kontekst**
Annen relevant informasjon

**Comment by magnusolderoesaether** [comment]
@mikaelbr 

"Denne billettvisningen er ikke gyldig ved eventuell billettkontroll. 
På reise vil det t:kortet du har registrert på din profil være gyldig billettbevis."

**Comment by mikaelbr** [comment]
Delvis dekt av #169 men 

2. Vurdere iterasjon av design
3. Tydeliggjøre i onboarding

dekkes ikke

**Comment by mikaelbr** [comment]
Lukker for nå med de tiltakene som er gjort. Testes i brukertester

**Comment by tormoseng** [comment]
Tekst på billettoversikten OK. Ellers brukertester. Flytter saken videre.
