### ISSUE TITLE
Tydeliggjøre inputfelt ved registrering av t:kort under onboarding

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#156]
Brukertest viser at det ikke er helt intuitivt for alle at t:kort-feltet i animasjonen ved registrering av t:kort er et inputfelt.
Vi bør se på hvordan vi kan gjøre det enda tydeligere - enten ved hjelp av UI eller copy.

**Comment by magnusolderoesaether** [comment]
Kan vi default lande i inputfelt ved innlasting av t:kort-steget her? Dersom vi har blinkende cursor i inputfelt tror jeg det er tilstrekkelig for å løse oppgaven

**Comment by mikaelbr** [comment]
Vi kan det.

**Comment by tormoseng** [comment]
Testet OK i staging
