### ISSUE TITLE
Validering av t:kort-nummer

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#157]
**Ved registrering av t:kort-nummer har vi peri dag ingen mekanisme for å validere/verfisere t:kort-nummer.
Dette kan medføre registrering av ugyldige nummer uten at bruker er klar over det, og bruker risikerer å reise med betalt billett men ugyldig billettbærer

---

**Comment by mikaelbr** [comment]
Her brukes Luhns algoritme: https://en.wikipedia.org/wiki/Luhn_algorithm

**Comment by mikaelbr** [comment]
Start 1616 er AtB, 70XX er eldre nummer. Avventer endelig bekreftelse om det stemmer.

**Comment by tormoseng** [comment]
Testet i staging.

@mikaelbr Spm:
- Ved feil inntastet t:kort-nr så blir feilmld: "Feilmelding fra tjenesten Travel card id is incorrect". Fint om dette var på norsk.
- Nysgjerrig. Tastet inn et tilfeldig tall som ble godkjent. Hvorfor går "2345678912345678" gjennom?

**Comment by mikaelbr** [comment]
😅  `2345678912345678` er gyldig tall jf. Luhn. Checksummen stemmer med fåregående signifikante tall. Så du kan fint taste inn et tilfeldig tall som stemmer, tilsvarende som du kan gjøre det med kredittkortnummer. Ulempen med dette er at vi ikke har en bekreftelsessteg som tar opp om du skriver inn et random-tall. Men det reduserer sjansene mye om du prøver å skrive inn en tallserie og bommer med ett tall (som er hensikten med algoritmen).

---

Jeg oversetter feilmeldingene. De henger igjen fra tidligere 😱

**Comment by mikaelbr** [comment]
For ytterlige validering burde vi se på startsiffer med AtB (1616) og nummervalidering på løpenummeret, men jeg har ikke helt fått landet alle detaljene der.

**Comment by mikaelbr** [comment]
@tormoseng Tekst skal være oppdatert nå i staging.

**Comment by tormoseng** [comment]
Testet OK i staging
