### ISSUE TITLE
[Feature] Egen billettkjøpsside for klippekort i staging

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#159]
**Konseptuell beskrivelse og behov som skal løses**

**Obs:** Venter design @pettersuul 
Miro for konsept: https://miro.com/app/board/o9J_lLJs9kk=/

Fra oversiktssiden skal man kunne klikke på en egen knapp for å komme til kjøpssiden for klippekort. På kjøpssiden for klippekort kan man se gyldige valg for billettypen og informasjon om antall klipp.

- [ ] Ny knapp fra oversiktssiden
- [ ] Rename eksisterende knapp til å være kjøp av spesifikt periodebillett
- [ ] Billettkjøpssiden viser Reisetype (disablet for nå)
- [ ] Billettkjøpssiden viser valg for reisende/passasjerkategori
- [ ] Billettkjøpssiden viser valg for soner
- [ ] Billettkjøpssiden viser infoboks om klippekort: antall klipp og hvordan disse tas i bruk.
- [ ] Henter ut og viser pris i oppsummering
- [ ] Betaling av billett

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Ses i sammenheng med #161

**Comment by magnusolderoesaether** [comment]
Kan vi delimplementere denne featuren slik at vi kan teste selve kjøpet av klippekort tidlig neste uke? Det er behov for å verifisere produktoppsettet hos Entur samt salgsrapporter/avgregning parallellt med at innholdet i fare contract gjøres ferdig?

**Comment by mikaelbr** [comment]
Ja. Jeg har gjort det nå slik at det er en "minimumsimplementasjon" med fungerende kjøp som kan merges inn i main og etterhvert til prod uten at det vises før vi har støtte for det. Det løser ikke hele denne oppgaven for vi skal få gjort oppsummeringssiden også.

**Comment by tormoseng** [comment]
@mikaelbr Knall! Men en ting jeg legger merke til nå er at sone ikke kommer med i oppsummeringen. Beklager at jeg ikke har sett det tidligere, men dette er vel vesentlig info om billetten som bør være med i oppsummeringen?

**Comment by tormoseng** [comment]
@mikaelbr Sonevelger ser litt rar ut på Edge og til dels Firefox (Mac OS)
Edge
<img width="591" alt="Screenshot 2021-06-28 at 08 41 57" src="https://user-images.githubusercontent.com/5812433/123592513-94e21e80-d7ed-11eb-9b9d-b2385baebff0.png">

Firefox
<img width="753" alt="Screenshot 2021-06-28 at 08 42 16" src="https://user-images.githubusercontent.com/5812433/123592539-9d3a5980-d7ed-11eb-9cf1-0f30d95f1044.png">

Noen sammenheng med hintet fra Edge i Inspect-modus? "meta[name=theme-color]' is not supported by Edge, Firefox, Firefox Android, Opera, Safari, iOS Safari." ?

**Comment by tormoseng** [comment]
Forøvrig så kommer Edge i Inspect-modus med flere Warnings og en Error på Security: "Response should include 'x-content-type-options' header." https://webhint.io/docs/user-guide/hints/hint-x-content-type-options/?source=devtools

**Comment by mikaelbr** [comment]
Warnings er nok pga noe annet! Men ang content type options så er det bra du sier det. Må ta en runde på headers og se på CSP (#271).

Skal se på feilen med Edge. Ser ut som det rett og slett er default CSS issue. Firefox er vel bare slik det blir i denne fasen tror jeg. Får du samme feil i Edge på macOS?

**Comment by mikaelbr** [comment]
https://github.com/AtB-AS/webshop/pull/272

**Comment by tormoseng** [comment]
> Skal se på feilen med Edge. Ser ut som det rett og slett er default CSS issue. Firefox er vel bare slik det blir i denne fasen tror jeg. Får du samme feil i Edge på macOS?

Allerede løst, ser jeg! Men, ja. Dette var Edge på macOS. #272 testet på macOS

**Comment by tormoseng** [comment]
Da er denne grei og kan flyttes videre!
