### ISSUE TITLE
[Feature] Gjennomføre kjøp av klippekort og visning av dette på oversikten i staging

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#160]
**Konseptuell beskrivelse og behov som skal løses**

**Obs**: Venter design @pettersuul 
Miro for konsept: https://miro.com/app/board/o9J_lLJs9kk=/

Fra billettkjøpssiden kan man foreta betaling via bankkort eller Vipps.

- [ ] Mulig å fullføre kjøp av klippekort
- [ ] Visning av kjøpte klippekort på oversiktssiden

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by hildeor** [comment]
Trenger design @pettersuul

**Comment by hildeor** [comment]
Miro for konsept: https://miro.com/app/board/o9J_lLJs9kk=/

**Comment by magnusolderoesaether** [comment]
Denne bør implementeres i to omganger.
1) Gjennomføre kjøp
2) Vise gyldig billett og status for klippekort

**Comment by pettersuul** [comment]
Forslag til design:
https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=1180%3A0
![image](https://user-images.githubusercontent.com/56530785/123793482-08655800-d8e2-11eb-94a7-bbf902c853b1.png)

**Comment by tormoseng** [comment]
@mikaelbr Nevnt muntlig, men med VO så får jeg ikke fokusert på billettdetaljene for en gyldig billett (eller en historisk billett)

**Comment by mikaelbr** [comment]
@tormoseng Jeg tror rett og slett dette er en bug/feil med iOS VO Safari som gjør at den ikke oppdager endringer i aria tags. Må finne en måte å unngå den buggen på, men ikke noe jeg får til på denne korte tiden. Foreslår at du noterer det som en egen bug (det gjelder egentlig fra før også).

**Comment by mikaelbr** [comment]
FYI: denne oppgaven er nå ute i prod men featuretogglet bort via remote config fare products

**Comment by tormoseng** [comment]
Da er denne saken god, og flyttes videre!
