### ISSUE TITLE
[Feature] Logikk for å håndtere billettkjøp basert på hvilke reiserettigheter man har (staging)

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#161]
**Konseptuell beskrivelse og behov som skal løses**

**Obs**: Venter design @pettersuul 
Miro for konsept: https://miro.com/app/board/o9J_lLJs9kk=/ 

Ettersom man bare kan ha ett produkt tilgjengelig på et t:kort til enhver tid, bør brukerne forhindres fra å foreta kjøp som ikke tillates av hardware.

- [ ] Hvis man har et aktivt periodeprodukt tilknyttet t:kortet disables knapp for kjøp av klippekort
- [ ] Disablet "kjøp klippekort"-knapp har medfølgende informasjon om hvorfor den ikke er tilgjengelig i nærheten av knappen
- [ ] Hvis man har et aktivt klippekort tilknyttet t:kortet disables knapp for kjøp av periodekort
- [ ] Disablet kjøp periodekort-knapp har medfølgende informasjon om hvorfor den ikke er tilgjengelig

**Annen nyttig kontekst**
Nevn annen nyttig informasjon og lenker som kan være viktig for denne oppgaven

Når mobiltoken er på plass må denne logikken også sees i sammenheng.
F. eks:
- [ ] Hvis mobiltoken er aktiv bærer så får man ikke kjøpt klippekort

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by magnusolderoesaether** [comment]
Vi må undersøke avhengige mellom APP og nettbutikk ved implementering av klippekort

**Comment by mikaelbr** [comment]
Ses i sammenheng med #159

**Comment by mikaelbr** [comment]
Blokkert inntil vi vet hva som skjer med begge produktene på tkortet.

**Comment by mikaelbr** [comment]
Det skal visst fungere fint å bruke periodekort og klippekort omhverandre. Dersom du har begge deler vil periodekort brukes hvor det er gyldig og klippekort om ikke.
