### ISSUE TITLE
[Bug] UU: Tastaturfelle ved lukking av enten datovelger eller tidsvelger under billettkjøp

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#165]
**Beskrivelse av bug**
Bruk av VoiceOver i Safari på iPad:
Havner i tastaturfelle når man lukker enten datepicker/timepicker:

Når du går ut av kalender eller tidsvelger, så havner man med et fokus som man ikke kan navigere seg fra uten å manuelt gå til annet element. Den leser også opp følgende som indikerer disablet element: “verktøylinje, tilbake, nedtonet, knapp”

**Reprodusering**
1. Gå til billettkjøp med VoiceOver aktivert
2. Gå til valg for gyldighet, velg "Velg dato og tid"
3. Åpne datovelger
4. Lukk datovelger
5. Prøv å sveip frem eller tilbake - fokus flytter seg ikke.
6. Vent 1-2 min, fokus flyttes deretter automatisk til neste element "soner".
I tillegg leser VoiceOver opp misvisende informasjon etter lukkingen om at knappen er nedtonet (dvs disablet).

**Forventet oppførsel**
Hvordan burde det egentlig fungere?
Sveip høyre/venstre flytter fokus frem/tilbake til forrige/neste element.

**Screenshots**
Vis video eller skjermbilde av feil.

**Desktop (please complete the following information):**
 - OS: iOS, med VoiceOver
 - Browser Safari

**Smartphone (please complete the following information):**

**Annen kontekst**
Annen relevant informasjon

**Comment by hildeor** [comment]
@mikaelbr Skal vi lukke denne iom. vi ikke får reprodusert med ny dato/tidsvelgere?

**Comment by mikaelbr** [comment]
Ja!
