### ISSUE TITLE
Legg til samtykke i onboarding

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#17]
- [x] Design finished for consents
- [x] Use new backend to store consents
- [ ] Update onboarding page to new design for showing initial consents 

![Screenshot 2021-05-19 at 10 18 45](https://user-images.githubusercontent.com/606374/118779696-997cf400-b88b-11eb-9079-ef399afa3f13.png)

## Samtykker

- Mulighet til å bli kontaktet.
- List for kontakt for brukertesting.

**Comment by mjenssen** [comment]
@magnusolderoesaether @pettersuul  Hva er de faktiske tekstene vi skal bruke her? Kun teksten for brukertester er listet i skjermbilde. Antar at den er grei, men hva med den andre? Opprinnelig var den "Jeg ønsker å bli kontaktet når endringer skjer i nettbutikken".

**Comment by tormoseng** [comment]
Ser bra ut. Et lite spm.

@mjenssen Jeg får ikke til å navigere meg til avhukingsfeltet med tastatur for å velge på eller av. Er det min mangel på kompetanse, eller en issue?

**Comment by mikaelbr** [comment]
Det mangler en outline som gjør at den ikke er synlig med fokus. Men det er navigerbart (aktivering skjer med space for skjema). Jeg kan fikse UU kjapt

**Comment by mikaelbr** [comment]
https://github.com/AtB-AS/webshop/pull/241

**Comment by mikaelbr** [comment]
Skal være oppdatert i staging nå og klar til ny test, @tormoseng
