### ISSUE TITLE
Oppdatere fra BETA-theme til offisielt AtB theme

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#172]
**Konseptuell beskrivelse og behov som skal løses**
Når vi går over i skarp drift er vi ute av BETA. Dette signaliserer vi med å endre theme fra "BETA". 

---

## Akseptansekriterier

- [ ] Nytt theme Implementert i designskisser
- [ ] Nytt theme testet OK I staging også med tanke på UU
- [ ] Timing for bytte avklart og avtalt med KD
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by pettersuul** [comment]
- Bytte bakgrunnsfarge i header til hvit.
- Bytte farge på CTA til blå med hvit tekst, og cyan fokus-outline.
- Oppdatere farger på states (hover o.l.).
- Bytte farge på meldingsboks til cyan og sort tekst.
