### ISSUE TITLE
[Bug] Økning av tekststørrelse gir ikke større tekst

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#175]
**Beskrivelse av bug**
WCAG 2.0 1.4.4 Endring av teksttørrelse: Ved å endre teksttørrelse på iOS/Android så blir ikke teksten i nettbutikken endret med et unntak for Android.

**Reprodusering**
1. Endre til stor teksstørrelse
2. Oppsøk nettbutikken

**Forventet oppførsel**
Nettbutikken bør vise tekststørrelse som angitt av enheten.

**Screenshots**
- Skjermbilde fra iOS 14 på iPhone (alle sider er like)
<img width="229" alt="Screenshot 2021-06-01 at 13 45 05" src="https://user-images.githubusercontent.com/5812433/120318016-99471480-c2df-11eb-8baa-a9e3def1e2a3.png">

- Skjermbilde fra Android etter å ha åpna billettdetaljer
<img width="252" alt="Screenshot 2021-06-01 at 13 44 19" src="https://user-images.githubusercontent.com/5812433/120317935-816f9080-c2df-11eb-829f-7e2f2b14f593.png">

- Skjermbilde fra Android etter å først ha åpna billettdetaljer, deretter navigert til f.ex min profil, for så å gå tilbake.
<img width="457" alt="Screenshot 2021-06-01 at 13 41 47" src="https://user-images.githubusercontent.com/5812433/120317646-2fc70600-c2df-11eb-8c8b-5798fce38594.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 12 mini + Samsung A5 (2016)
 - OS: iOS 14.4.2 + Android 7.0
 - Browser Chrome

**Comment by mikaelbr** [comment]
Se kommentar fra https://github.com/AtB-AS/webshop/pull/176:

> Legger om til å bruke nettleseren standards størrelse og heller ha resten av størrelsene relativ i forhold til den. Dette fikser derimot ikke skalering ved bruk av "Tilgjengelighet" i iOS. Så vidt meg bekjent (mulig jeg tar feil her), så påvirker ikke den tekst i nettleseren. Det finnes en egen feature i Safari (enten via adresselinjen eller settings for Safari) som setter overrides for størrelser og andre ting.

**Comment by tormoseng** [comment]
Denne er god!
