### ISSUE TITLE
[Bug] Overskrifter blir ikke lest opp riktig i VoiceOver

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#177]
**Beskrivelse av bug**
Ved bruk av VoiceOver i Safari så leses enkelte overskrifter opp med feil tekstlig innhold.
På Android fungerer det som forventet i både onboarding og Kjøpshistorikk.

Gjelder:
- Steg 2 og 3 i onboarding
- Kjøpshistorikk

**Reprodusering**
1. Aktiver VoiceOver/talkback
2. Gå til kjøpshistorikk
3. Flytt fokus til overskriften "Kjøpshistorikk"
4. Nå leses det opp "Min profil".

I onboardingen så leses overskriften fra steg 1 opp når man fokuserer på overskriftene i steg 2 og 3.

**Forventet oppførsel**
Bør lese opp samme tekst som visuelt er synlig.

**Smartphone (please complete the following information):**
 - Device: iPad pro
 - OS: 14.4.2
 - Browser Safari

**Annen kontekst**
Har testet på iOS i Chrome og da leses Kjøpshistorikk opp riktig.

**Comment by gorandalum** [comment]
Fått reprodusert dette i både Safari og Chrome på min iPhone. Jeg ser på det.

**Comment by tormoseng** [comment]
Testet OK i staging
