### ISSUE TITLE
Ask for travel card during onboarding

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#18]
- [x] Design for travel card during onboarding
- [ ] Call register to add travel card to your profile
- [ ] Handle errors

Etter lagring av samtykker får bruker mulighet til å legge til et eksisterende t:kort. Bruker får god informasjon om hvilke konsekvenser dette har for eventuelt eksisterende billetter i Faras nettbutikk. 
Legge til t:kort-nummer > Navngi t:kort > Velge "Legg til" t:kort.
Bruker tilbys muligheten til å hoppe over sekvensen.

**Comment by pettersuul** [comment]
![image](https://user-images.githubusercontent.com/56530785/116517068-b5195e00-a8ce-11eb-8c17-818099ff15b4.png)
![image](https://user-images.githubusercontent.com/56530785/116517080-b9de1200-a8ce-11eb-8246-279120cf1d90.png)
![image](https://user-images.githubusercontent.com/56530785/116517094-bcd90280-a8ce-11eb-8d34-9bc35f3152a2.png)

**Comment by magnusolderoesaether** [comment]
Synes dette ser bra ut som konsept, men det er litt for utydelig hva som faktisk er input-felt. Foreslår border og/eller bakgrunnsfarge slik at bruker opplever det som standard inputfelter

**Comment by pettersuul** [comment]
![image](https://user-images.githubusercontent.com/56530785/116521993-f1e85380-a8d4-11eb-9870-8367fcabb279.png)
![image](https://user-images.githubusercontent.com/56530785/116522010-f4e34400-a8d4-11eb-8aac-e20b87f5a84e.png)
![image](https://user-images.githubusercontent.com/56530785/116522018-f7459e00-a8d4-11eb-9978-b154752b1d68.png)

**Comment by magnusolderoesaether** [comment]
mer noe slikt jeg tenkte på 
![image](https://user-images.githubusercontent.com/50573205/116523879-01689c00-a8d7-11eb-971f-9be6955d816c.png)

**Comment by tormoseng** [comment]
Testet OK for Chrome og Safari på Mac OS

@mikaelbr For Safari på iOS ble "Tilbake" og "Hopp over ..." lagt over hverandre når man går fullfører steg 1
![onboarding_safari_ios](https://user-images.githubusercontent.com/5812433/118684093-385d0e00-b802-11eb-8764-4adf2d6ebdaa.jpg)

Når jeg kom til App-info-bildet og trykket "Tilbake" så ble alt fullført - men det er mulig at jeg faktisk trykket på "Hopp over..." når disse lå over hverandre.

Ellers OK på Safari iOS. All info blir lagt inn på profilen.

**Comment by mikaelbr** [comment]
Egen bug: https://github.com/AtB-AS/webshop/issues/128
