### ISSUE TITLE
Inkonsekvente definisjoner av lenker i hovednavigasjon

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#180]
**Beskrivelse av bug**

Hovednavigasjon: Kjøp billett, Kjøpshistorikk og Min profil leses opp inkonsekvent. Kjøp billett leses opp som navgiasjonselement, men det blir ikke de to siste.

**Reprodusering**
1. Aktiver VoiceOver
2. Flytt fokus til Kjøp billet, Kjøpshistorikk og Min profil.

**Forventet oppførsel**
Hvordan burde det egentlig fungere?

Alle bør ha samme definisjon som navigasjonselement

**Comment by gorandalum** [comment]
Ikke noe feil her. Det første og siste menyobjektet leses litt forskjellig siden skjermleseren også leser opp at navigasjons-elementet starter/slutter, og at det er et landemerke.
