### ISSUE TITLE
Steg 3, onboarding: knapper mangler informasjon

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#182]
**Beskrivelse av bug**
WCAG 2.0 2.4.4 Formål med lenke (i kontekst)

Lenkene som leder til hhv. App Store og Google Play, trenger tekst-oppdatering. 
Sier nå: 
"iOS badge, lenke. Se AtB Beta i app store."
"Android badge, lenke. Se AtB Beta i Google Play Store." 

Fullfør-knapp spesifiserer ikke hva man fullfører i VoiceOver-modus.
﻿

**Forventet oppførsel**
- Beta-begrepet bør tas bort, og teksten bør spesifisere følgende:
- App store: Ta bort beta-begrep, spesifiser at lenken åpner App store.
- Google Play: Ta bort beta-begrep, spesifiser at  den åpnes i Google Play.
- Fullfør-knapp: legg på info som spesifiserer hva som fullføres, e.g. "Fullfør, aktiver for å avslutte onboarding, knapp".

**Comment by hildeor** [comment]
@magnusolderoesaether FYI, i fall du har noe innspill til språk her.

**Comment by tormoseng** [comment]
Testet OK i staging på iOS + Android
