### ISSUE TITLE
Lenker inneholder riktig informasjon - kjøp billett

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#183]
**Beskrivelse av bug**

-På lenken til sonekart leses det også opp info om sonevalgene man har gjort, noe som ikke er relevant for fokus på denne lenken.

- Knapper som tar deg til betaling som tar deg ut av kontekst bør opplyse om dette. 

**Forventet oppførsel**
- Fokus på lenken til sonekart og beskrivelser leser ikke opp aktivt sonevalg.
- Knapper for å kjøpe med enten bankkort eller Vipps annonserer at du tas videre til betaling

**Comment by gorandalum** [comment]
> På lenken til sonekart leses det også opp info om sonevalgene man har gjort, noe som ikke er relevant for fokus på denne lenken.

Dette får jeg ikke reprodusert. Trolig fikset? Testet med VoiceOver på Mac og iOS.

> Knapper som tar deg til betaling som tar deg ut av kontekst bør opplyse om dette.

Har gjort noen endringer på dette i tilhørende PR. Knappen var implementert som en html `<button>`, men jeg har nå endret det til `<link>` siden det blir mer riktig. Jeg har også lagt på en a11y label slik at den sier "Gå til betaling med vipps/visa/mastercard". Jeg tenker vi da er innenfor opplysningsplikten til brukeren om at knappen går til ny kontekst.

**Comment by tormoseng** [comment]
Testet OK.
Får heller ikke reprodusert pkt.1 med hverken VoiceOver eller TalkBack.
