### ISSUE TITLE
Korte ned lenkeinformasjon

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#184]
**Beskrivelse av bug**
[iOS/Safari/iPad] 
Alle lenker for å gå tilbake til "Oversikt":
Knappen for å gå tilbake til "Oversikt" leser opp ganske mye informasjon. Blant annet "Oversikt, besøkt. Lenke. Hoved, Landemerke. Handlinger tilgjengelig." 
Hva kan kortes ned på her?

**Comment by gorandalum** [comment]
Lite vi får gjort med dette, for eksempel blir første/siste element i `<main>`lest som "Hoved"/"Hoved slutt". 
Men dette er ikke unikt for oss, samt at det skal være til hjelp for brukeren til å vite hvor man er på siden.
