### ISSUE TITLE
Mangler hovednavigasjon på mindre skjermstørrelser

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#186]
**Beskrivelse av bug**
WCAG 2.0 2.4.5 Flere måter (å navigere på)

Hovednavigasjonen skjules hvis skjermen når en viss minste størrelse. Dette gjør at vi ikke får ivaretatt krav om å ha flere måter å navigere til innhold på.

**Reprodusering**
1. Besøk nettbutikken fra mobiltelefon

**Forventet oppførsel**
Hovednavigasjon komprimeres i egen knapp på skjermstørrelser hvor det ikke er plass til horisontal navigasjonsbar.
@pettersuul Formening om design her?

**Comment by hildeor** [comment]
<img width="320" alt="Navigation --closed" src="https://user-images.githubusercontent.com/8980523/123970169-2ea9f700-d9b9-11eb-8dd3-f9298de629ea.png">
<img width="320" alt="Navigation --open" src="https://user-images.githubusercontent.com/8980523/123970172-2f428d80-d9b9-11eb-900f-9ac48b944458.png">

Figma: https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=1226%3A16124

**Comment by tormoseng** [comment]
Testet OK i staging
