### ISSUE TITLE
Dato leses ikke opp som dato - kjøpshistorikk

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#187]
**Beskrivelse av bug**

VoiceOver identifiserer ikke opp dato på et item i kjøpshistorikken som dato, og leses dermed opp numerisk.

**Forventet oppførsel**
Dato på hvert enkelt kjøp i historikken leses opp som dato.

**Comment by tormoseng** [comment]
Testet OK. 
@gorandalum For ordens skyld så leser TalkBack opp datoene helt fint. Oversetter f.ex 05.01 til "5. januar".
