### ISSUE TITLE
Tydeliggjøre markerte valg i billettkjøpsprosessen

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#188]
**Beskrivelse av bug**
iOS: Her kan VoiceOver med fordel tydeliggjøre hvilke valg som er tatt. F. eks så leses det opp "Reisetype buss og trikk ........ " men det ville vært tydeligere at det er en status som er valgt hvis man hadde lest opp "Reisetype, buss og trikk er valgt".
Samme gjelder de andre valgene.

**Forventet oppførsel**
Ved fokus på headingene til de ulike valgene, leses følgende opp:
<overskrift>, <valgt verdi> er valgt

Eksempel:
Reisetype, buss og trikk er valgt
Billettype, 30 dagers billett er valgt
Reisende, 1 voksen er valgt
Gyldig fra og med, kjøpstidspunkt er valgt
Soner, sone A til sone C5 er valgt.

**Comment by gorandalum** [comment]
Endret dette slik at "er valgt" blir satt i aria-label bak de valgene som er mulig å endre. Også endret soneteksten til å være mer utfyllende.

Eksempler på hvordan det etter endringen blir lest opp på min maskin:
- "Reisetype, buss og trikk, dimmed, collapsed, button"
- "Billettype, 30 dagers billett er valgt, endre varighet, collapsed, button"
- "Gyldig fra og med, kjøpstidspunkt er valgt, endre tid, collapsed, button"
- "Soner, reise i en sone (A) er valgt, group"
- "Soner, reise fra sone D til sone B1 er valgt, group"

**Comment by tormoseng** [comment]
@gorandalum Testet OK med et spm

> "Soner, reise i en sone (A) er valgt, group"
"Soner, reise fra sone D til sone B1 er valgt, group"

Jeg får ikke lest opp dette på kjøpssiden, der leses det kun opp hva som er satt for avgangssone og deretter for ankomstsone etter å ha flyttet fokus. Får ikke markert hele sone-feltet om det er dette som er poenget. Gjelder både VoiceOver (Safari) og TalkBack (Chrome)

**Comment by tormoseng** [comment]
Diskutert med @gorandalum ☝️ . Denne er OK
