### ISSUE TITLE
Mulighet til å enkelt legge til/fjerne et t:kort etter onbarding

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#19]
Brukere som ikke har laget til t:kort under onboardingen må enkelt finne en flyt for å registrere og bekrefte et nytt t:kort på sin profil.

## Akseptansekriterier

- [x] Fungerer med tastaturnavigasjon
- [x] Bruker rette farger og størrelser iht. design system
- [x] Gir feilmeldinger om det ikke er mulig å legge til eller fjerne.
- [x] Kan kun fjerne om du har fra før, eller legge til om du ikke har.
- [x] Gir god nok advarsel ved fjerning.
- [x] Fungerer i alle store evergreen nettlesere.
- [x] Fungerer i alle størrelser og flater (mobil, desktop, etc).

---

- [x] Design for managing travel card in account page
- [x] UI and call backend to add a new travel card
- [x] UI and call backend to remove existing travel card
- [x] Handle updating by removing and adding (?)
- [x] Handle errors

<img width="962" alt="Screenshot 2021-04-21 at 11 42 41" src="https://user-images.githubusercontent.com/606374/115533076-af03fb80-a296-11eb-91b5-55c5d1d3798b.png">
<img width="535" alt="Screenshot 2021-04-21 at 11 42 51" src="https://user-images.githubusercontent.com/606374/115533104-b4f9dc80-a296-11eb-8cec-3ed59a4b83d0.png">

**Comment by mikaelbr** [comment]
Kun mulig å fjerne om du har før. Vil du endre må du fjerne først.

**Comment by tormoseng** [comment]
Happy day testet OK i staging med div. browsere.

Observasjoner:
- Ved å legge inn “123456789” så fremkommer “unknown error”. Kallet POST /webshop/v1/travelcard gir 409 og responsen “{”error”:“Travelcard is linked to another account.“}”
- På oversiktssiden står fortsatt statiske “Ingen reisekort”
- Overskrift “Kontoinformasjon” legges over “<- Oversikt” ved mobilvisning

**Comment by tormoseng** [comment]
@mikaelbr se observasjoner over ☝️

**Comment by mikaelbr** [comment]
> På oversiktssiden står fortsatt statiske “Ingen reisekort”

Egen issue: #82

**Comment by mikaelbr** [comment]
Rapporterte feil utbedres: https://github.com/AtB-AS/webshop/pull/84

**Comment by mikaelbr** [comment]
Skal være klar for retesting ved deploy nå, @tormoseng

**Comment by tormoseng** [comment]
Re-testet OK etter #84

**Comment by magnusolderoesaether** [comment]
Copy: 
Feltbeskrivelse: "t:kort-nummer (16 siffer)
Feilmelding: "t:kort-nummeret du har skrevet inn er enten feil eller allerede registrert på en annen profil"

<img width="619" alt="image" src="https://user-images.githubusercontent.com/50573205/117010203-daea9c80-acec-11eb-8d33-a25437379a77.png">

**Comment by magnusolderoesaether** [comment]
Knapp: "Legg til" i stedet for "Lagre"
