### ISSUE TITLE
W3C validator gir CSS-feil

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#192]
**Beskrivelse**
WCAG 2.0 4.1.1 går på parsing av siden. Her er jeg usikker på om denne retter seg spesifikt mot HTM-en, eller om CSS også inkluderes her.

Ved å "kjøre" staging url gjennom W3C sin validator er det ingen feil på HTML, men vi får 17 feil på CSS. Se gjerne over resultatet her: https://validator.w3.org/unicorn/check?ucn_uri=https%3A%2F%2Fatb-webshop-staging.web.app%2F&ucn_task=conformance#

**Comment by gorandalum** [comment]
Dette er fordi css-valideringen på den validatoren ikke støtter SVG. W3C har en også en egen [css-validator](https://jigsaw.w3.org/css-validator/) med flere tilpasningsmuligheter. Velger man der profilen "CSS Level 3 + SVG" så får vi ingen css-errors:
https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fatb-webshop-staging.web.app&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en
