### ISSUE TITLE
Feilemeldinger i innlogging mangler forslag 

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#199]
**Beskrivelse av bug**
- Mangler forslag ved feil når man taster inn ugyldig telefonnummer. Feilmeldingen sier "Ugyldig telefonnummer". 
Forslag: Legg på "Sjekk at telefonnummeret består av 8 siffer."
- Ved innstasting av feil engangspassord foreslås følgende omskriving av feilmelding: "Passordet stemmer ikke, vennligst sjekk at det er riktig passord eller be om et nytt engangspassord."﻿

**Forventet oppførsel**
- Ugyldig telefonnummer: "Ugyldig telefonnummer. Sjekk at telefonnummeret består av 8 siffer."
- Feil engangspassord: "Passordet stemmer ikke, vennligst sjekk at det er riktig passord eller be om et nytt engangspassord."﻿

**Comment by gorandalum** [comment]
@hildeor Angående teksten på feil kode så er det "engangskode" og ikke "engangspassord" som er brukt i webshopen.

Passer denne teksten?
"Koden stemmer ikke, vennligst sjekk at det er riktig kode eller be om en ny engangskode."

**Comment by tormoseng** [comment]
Testet OK i staging
