### ISSUE TITLE
Add all details in summary pane while shopping

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#20]
Gi en komplett oversikt over kjøp. Hypotese at det holder å vise oppsummering i velgeren som vist i bildet og bare ekstra-informasjon som MVA og gyldighetsperiode i selve oppsummeringsvisningen.

Foreløpig design-skisser:

![Screenshot 2021-04-28 at 14 17 46](https://user-images.githubusercontent.com/606374/116402287-834fbb00-a82c-11eb-8187-f5135e074f3d.png)

![Screenshot 2021-04-28 at 14 18 01](https://user-images.githubusercontent.com/606374/116402313-8c408c80-a82c-11eb-8424-033cd1f01720.png)

- [ ] Viser korrekt MVA sum
- [ ] Tall er formatert etter norsk standard med 2 desimaler.
- [ ] Viser korrekt gyldighet i korrekt tidssone.
- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir tydelig feilmelding gitt at kjøp feiler.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).
- [ ] Gir en loading indicator som ikke forstyrrer for mye men gir indikasjon på endring.

**Comment by magnusolderoesaether** [comment]
Her er det vel en designendring på trappene hvor kun kostnad blir med i oppsummeringsfeltet. Informasjon om billettegenskapene vil vises i "konfiguratoren". @mikaelbr skal denne sendes tilbake til Feature refinement?

**Comment by mikaelbr** [comment]
Ja, kan gjøre det. Men da heller ikke en del av 1. pilot?

**Comment by mikaelbr** [comment]
Kunne ikke enkelt hente ut "gyldig til" før et kjøp faktisk er gjennomført. Som gjør det vanskelig å vise det i oppsummeringen.

**Comment by magnusolderoesaether** [comment]
Gyldig til: x antall dd:tt:mm etter betaling?
