### ISSUE TITLE
Alternativ beskrivelse av billettikon på Oversikt

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#209]
**Beskrivelse**
En gyldig billett vil nå identifiseres med et grønt billett-ikon. Teksten på en billett sier f.ex "29 dager igjen", men her bør billettikonet kunne inngå i opplesing a la "Gyldig i 29 dager". Se også #198 for mulighetene rundt utvidet info omkring bruk av "aria-labelledby"

**Comment by gorandalum** [comment]
Det ble lagt inn beskrivelser for ikonene før sommeren av Mikael.
