### ISSUE TITLE
Spesifisere formål med lenker under Min profil

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#218]
**Beskrivelse av bug**
WCAG 2.0 2.4.4 Formål med lenke (i kontekst).

- [iOS/Safari] Ved valg av "legg til t:kort" fra hovedside så åpnes riktig redigeringsvalg for t:kort, men voiceover leser opp mobilnummer under innloggingsmetode (som for 88889999 er "ikke utfylt"), som også får fokus
- [iOS/Android] Lenke til personvernerklæring kunne gitt info om hvor denne lenken går til, f.ex hvilket domene.
- Knappen for å gå tilbake til "Oversikt" leser opp ganske mye informasjon. Blant annet "Oversikt, besøkt. Lenke. Hoved, Landemerke. Handlinger tilgjengelig." Kan kortes ned til "gå tilbake til oversikt, lenke".
- [Android/Chrome] Markering av "Oversikt" gir bare talemld "Oversikt link". Savner info om type "link til oversiktssiden" el.lign
- [iOS/Android] Lenke til personvernerklæring burde gitt info om hvor denne lenken går til, f.ex hvilket domene.
- iOS/Android: Lenke til å bestille nytt skjema tar deg til et nytt domene, i en ny fane. Dette bør spesifiseres via VOiceOver/talkback. "...bestille her" bør kanskje også spesifiserer med "..bestille på atb.no."﻿

**Comment by gorandalum** [comment]
> [iOS/Safari] Ved valg av "legg til t:kort" fra hovedside så åpnes riktig redigeringsvalg for t:kort, men voiceover leser opp mobilnummer under innloggingsmetode (som for 88889999 er "ikke utfylt"), som også får fokus

Dette er pga. logikken vi la inn med at overskrift får fokus når man kommer på konto-siden. Jeg har fikset dette i lenket PR slik at hvis man skal direkte inn å redigere på noe så fokuserer man ikke på overskrift.

> [iOS/Android] Lenke til personvernerklæring kunne gitt info om hvor denne lenken går til, f.ex hvilket domene.

Denne har fått ekstra tekst "åpner nytt vindu", så jeg tenker det er bra nok

> Knappen for å gå tilbake til "Oversikt" leser opp ganske mye informasjon. Blant annet "Oversikt, besøkt. Lenke. Hoved, Landemerke. Handlinger tilgjengelig." Kan kortes ned til "gå tilbake til oversikt, lenke".

Skjermleser-tekniske greier som vi ikke får omgått uten å nedgradere semantikken i html-en vi bruker.

> [Android/Chrome] Markering av "Oversikt" gir bare talemld "Oversikt link". Savner info om type "link til oversiktssiden" el.lign

"Oversikt, link" blir i praksis likt med "link til overssikt", så det er ikke så stort avvik at jeg gjør noe med det nå.

> [iOS/Android] Lenke til personvernerklæring burde gitt info om hvor denne lenken går til, f.ex hvilket domene.
 
>[iOS/Android: Lenke til å bestille nytt skjema tar deg til et nytt domene, i en ny fane. Dette bør spesifiseres via VOiceOver/talkback. "...bestille her" bør kanskje også spesifiserer med "..bestille på atb.no."﻿

Begge har tekst "åpner nytt vindu"/"åpner ny side" som er bra nok for nå.

**Comment by tormoseng** [comment]
Testet OK
