### ISSUE TITLE
Gi informasjon om feil som oppstår under redigering av Min profil

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#220]
**Beskrivelse av bug**
WCAG 2.0 3.3.1 Identifikasjon av feil:

> Ved feil i utfylling av skjema, skal brukaren få informasjon, både om at ein feil har oppstått og kva feilen er. Feilmeldinga skal vere gitt i form av tekst og vere så spesifikk som mogleg. Dette omfattar også informasjon om kvar i skjemaet feil har oppstått.﻿

-  [iOS/Android] feilmelding ved lagring av **t:kort** blir ikke opplest. Det skjer ingenting når man gjentatte ganger trykker lagre (når man da ikke ser feilmld). I tillegg refererer feilmeldingen til "t:kort id". Bør referere til t:kortnummer som er label til feltet.
- [iOS/Android] feilmelding ved lagring av **epost** blir ikke opplest. Det skjer ingenting når man gjentatte ganger trykker lagre (når man da ikke ser feilmld)
- [iOS/Android] feilmelding ved lagring av **navn/etternavn** blir ikke opplest. Det skjer ingenting når man gjentatte ganger trykker lagre (når man da ikke ser feilmld). Den feilmeldingen som dukker opp hvis man prøver å trykke lagre uten å fylle ut navn er også utformet ulikt andre feilmeldinger.
- Hvis man prøver å redigere epost får man "Unknown error"
- Man får ikke lov til å lagre blank epost. Det bør være mulig å fjerne denne etter man har lagret epost.﻿

**Comment by gorandalum** [comment]
Dette er i hovedsak forbedret:
- Alle advarsler leses opp når de dukker opp. De leses ikke på nytt ved neste klikk på "Lagre" hvis ikke noe er endret, men tenker det ikke er så kritisk.
- Får ikke reprodusert "Unknown error". Jeg har fått redigert min epost-adresse.
- Får lov til å lagre blank epost.
