### ISSUE TITLE
Ledetekster/instruksjoner i onboarding

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#221]
**Beskrivelse av bug**
WCAG 2.0 3.3.2 Ledetekster eller instruksjoner

- (iOS/Safari/iPad) Fornavn, etternavn og epost blir alle lest opp av VoiceOver som "kreves", men i praksis er de ikke det og man kan bare klikke neste uten å fylle ut feltene.
- (iOS/Safari/iPad) Når man har begynt å skrive i telefonnummerfeltet, flytter fokus og så går tilbake for å redigere, så settes markøren i starten av telefonnummeret. Kan man force denne til å starte bakerst?

**Comment by gorandalum** [comment]
Fikset at onboarding-felter ikke leses opp som required i lenket PR. Det med markøren er ikke prioritert nå.

**Comment by tormoseng** [comment]
Fungerer fint!

@gorandalum Vet ikke om det er annen sak, men samme "kreves" leses også opp for steg 3 på input for t:kort.

**Comment by gorandalum** [comment]
@tormoseng Det er en forskjell her. "Neste" fungerte på det første onboarding-skjermbildet likevel om navn ikke var utfylt. På skjermbildet med t:kort kan man ikke trykke "Legg til t:kort" med tomt input-felt, da får man valideringsfeil. Så jeg tenker det er riktig at feltet står som påkrevd, likevel om det er mulig å komme seg rundt det med "Hopp over".
