### ISSUE TITLE
Skjermleseropplesing av ledetekster/instruksjoner på oversiktsiden

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#222]
**Beskrivelse av bug**
WCAG 2.0 3.3.2 Ledetekster eller instruksjoner

- [iOS/Safari] Opplesing av ordre-id går "i ett", dvs voiceover prøver å lese et ord ut av denne. Ordre-id bør leses opp bokstav for bokstav.
- [Android/Chrome] her leses bokstavene, men altfor raskt

**Comment by gorandalum** [comment]
Dette ble fikset av #225
