### ISSUE TITLE
Ledetekster/instruksjoner ved Kjøp av billett

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#223]
**Beskrivelse av bug**
WCAG 2.0 3.3.2 Ledetekster eller instruksjoner

- Valg av gyldighetstidspunkt: bør fremgå tydeligere at man her kan velge når billetten blir gyldig. F. eks valget "Kjøpstidspunkt" kan utvides til å også lese opp "dobbeltrykk for å sette gyldighet på billetten til kjøpetidspunkt".
- iOS (kanskje Android): Ved fokus på "Velg dato og tid", uten å markere denne radioknappen og deretter sveiper en gang til høyre, så leses det opp informasjon som ikke er relevant for skjemaet.
- [Android/Chrome] ingen info om at Reisetype er disablet (eller nedtonet slik som VoiceOver bruker)
- [iOS/Safari] trykk på radio-box gir en opplesing av underteksten, f.ex for barn "Person 4-15 år" i stedet for å gi en beskrivelse a la "Barn. Aktiver for å velge barn som resisende". Samme gjelder også valg under billettype; ingen info om å trykke for å velge billettype.
- [Android/Chrome] Markering av alternativer her sier opp "Barn Person 4-15 år ikke valgt".
- [iOS/Android] alle valg gir talebeskjed om å "dobbelttrykk for å utvide". Kunne hatt info om "dobbelttrykk for å velge/endre x"

**Comment by gorandalum** [comment]
Jeg har generelt gjort noen forbedringer her i forbindelse med fokus på disse skjemaelementene. Det var en del kluss med at i html-en var det `h3` som hadde en `button` som underelement, og da ble skjermleserene litt forvirret om de skulle håndtere det som header eller button. Jeg endret nå til at det kun er button, og det virker da som at det fungerer bedre.

> Valg av gyldighetstidspunkt: bør fremgå tydeligere at man her kan velge når billetten blir gyldig. F. eks valget "Kjøpstidspunkt" kan utvides til å også lese opp "dobbeltrykk for å sette gyldighet på billetten til kjøpetidspunkt".

Har fikset teksten nå til å være for eksempel "Reisende, 1 honnør, endre reisende" og "Gyldig fra og med, kjøpetidspunkt, endre tid". Jeg tenker det er greiest å utelate "Dobbelttrykk for å ..." eller "Aktiver for å ..." i teksten vi spesifiserer, siden dette ofte blir lest opp av skjermleseren.

> iOS (kanskje Android): Ved fokus på "Velg dato og tid", uten å markere denne radioknappen og deretter sveiper en gang til høyre, så leses det opp informasjon som ikke er relevant for skjemaet.

Denne får jeg ikke reprodusert på OSX eller iOS. Synes det fungerer greit nok.

> [Android/Chrome] ingen info om at Reisetype er disablet (eller nedtonet slik som VoiceOver bruker)

Reisetype var i praksis bare tekst. Endret nå slik at den også er en knapp, som leses opp som nedtonet.

> [iOS/Safari] trykk på radio-box gir en opplesing av underteksten, f.ex for barn "Person 4-15 år" i stedet for å gi en beskrivelse a la "Barn. Aktiver for å velge barn som resisende". Samme gjelder også valg under billettype; ingen info om å trykke for å velge billettype.

Det ble gjort noen forbedringer på radio-knapper i en tidligere sak. Jeg synes dette fungerer greit nok nå.

> [Android/Chrome] Markering av alternativer her sier opp "Barn Person 4-15 år ikke valgt".

Har ikke Android å teste på, men håper at det også har blitt fikset når det ble generelt fikset litt på radio-knapper.

> [iOS/Android] alle valg gir talebeskjed om å "dobbelttrykk for å utvide". Kunne hatt info om "dobbelttrykk for å velge/endre x"

Disse beskjedene om å dobbelttrykk for å utvide er fordi vi har satt `aria-expanded` på knappen, som sier til skjermleseren at knappen styrer en expandable. Selve teksten som leses opp er ikke styrt av oss.

**Comment by tormoseng** [comment]
Synes denne er grei nå. Testet på iOS/VO og Android/TB i staging.
