### ISSUE TITLE
Enkelt valg av sone i billettkjøpsflyten

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#25]
- [ ] Design er klart
- [ ] Velg sone fra en kartvisning
- [ ] Bekreft valgt sone i kartvisning

**Comment by magnusolderoesaether** [comment]
Splittes opp I quick fix med statisk bilde, og dynamisk kartvalg

**Comment by jahnrohme** [comment]
Ikke aktuelt p.t
