### ISSUE TITLE
[Bug] Låse innlogging og brukeropprettelse til norsk landskode på telefon

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#254]
Entur har kun støtte for `+47`-nummer men vi har støtte for flere. Det kan skape problemer. Vi burde låse fast slik at det kun er mulig med norsk nummer (eller epost).

**Comment by mikaelbr** [comment]
Det stemmer ikke at Entur har kun støtte for +47, men Vipps som betalingsmetode vil ikke fungere. Men folk som har ikke-NO nummer kan fremdeles registrere seg og ha kort som er betalt via Nets.

**Comment by tormoseng** [comment]
@mikaelbr Det meste ser bra ut i staging.

En ting jeg ikke fant sist er om du setter telefonnummer til f.ex "+4791821" i minprofil (som epost-bruker) så får man feilmld "Det skjedde en feil med tjenesten. Prøv igjen senere", mens kallet bakover kommer med HTTP 500 og beskjeden "Norske telefonnummer må ha 8 siffer".

**Comment by tormoseng** [comment]
Relatert til https://github.com/AtB-AS/webshop/issues/290#issuecomment-875541346 ☝️
