### ISSUE TITLE
Component: Date picker

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#29]
- [ ] Design ready
- [ ] Should handle quickly changing to different month or year
- [ ] Regler for hvor langt frem i tid man kan sette starttidspunkt må tydeliggjøres i implementasjonen slik at bruker ikke har anledning til å (forsøke å) velge en ugyldig startdato/tidspunkt

**Comment by jahnrohme** [comment]
Denne er vel fikset?
