### ISSUE TITLE
[Improvement] Bedre feilmelding når man legger til et eksisterende t-kort

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#290]
**Beskrivelse av bug**
Hvis man i Min Profil legger til et t:kort som allerede er registrert på noen andre så får POST /travelcard HTTP 500 med beskjeden "{"error":"Internal error.","upstreamError":"AlreadyExists: Entity already exists: TravelCard with id: 691250417 is already registered as a token."}", mens brukeren får beskjeden "Det skjedde en feil med tjenesten. Prøv igjen senere."

Her vil det ikke hjelpe å prøve igjen senere.

Testet på staging.

**Comment by mikaelbr** [comment]
Ser ut til å være en endringsfeil i backend: https://github.com/AtB-AS/webshop-backend/blob/747f48a3efc92c0f734b1dd6220eb1753d8ed81b/http/errors.go#L39

**Comment by havwig** [comment]
Stemmer det at problemet er ca sånn: Frontend forventer å få HTTP 409 (Conflict) når man prøver å registrere et eksisterende kort. Dette er også responsen fra Entur, men pga feilhåndtering i webshop-backend så får klient HTTP 500 i stedet?

**Comment by mikaelbr** [comment]
Frontend forventer 409 og har tidligere fått 409, ja. Men det er noe som har skjedd som gjør at webshop-backend bare sender 500. Dette gjelder også ved oppdatering av epost.

**Comment by tormoseng** [comment]
Samme problem hvis man legger inn ugyldig telefonnummer i onboarding. HTTP 500 med body som inneholder "Norske telefonnummer må ha 8 siffer", mens webshop kaster:
![Screenshot 2021-07-09 at 11 44 03](https://user-images.githubusercontent.com/5812433/125059176-54b35380-e0ab-11eb-8c96-3d151e4a4615.png)

**Comment by tormoseng** [comment]
Også ved innlegging av ugyldig telefonnummer på min profil.

**Comment by mjenssen** [comment]
Har verifisert at man får 409 i webshop i staging igjen når man prøver å legge til t:kort som eksisterer. Får en feilmelding som gir mening.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/23308/133752921-5bbce04c-993a-4505-ab3b-e9bad7fef9d5.png">

**Comment by mjenssen** [comment]
> Også ved innlegging av ugyldig telefonnummer på min profil.

Telefonnummer er litt rar. Det er ikke alle norske telefonnummer som gir feil. Masse 0er gir ikke feil i det hele tatt f.eks.

**Comment by cbrevik** [comment]
Denne er vel løst?
