### ISSUE TITLE
Valg av theme fra profilside

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#307]
Mulighet for å velge light eller dark theme fra profilside. Enten lagres på device (`localStorage`) eller som del av profilen (kan muligens bruke settings-APIet til Entur). Sistnevnte krever backendjobb også.

Se #232 for hvordan selve overriden må gjøres.

**Comment by mikaelbr** [comment]
aside: Settings burde være individuell på app og nettbutikk (forskjellige behov).
