### ISSUE TITLE
[Bug] Safari iOS VoiceOver + inert slår noen ganger feil ut

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#310]
**Beskrivelse av bug**
Det virker til å være en bug i iOS Safari med VoiceOver som gjør at noen ganger fanger den ikke opp endringer i DOM-treet ved attributtendringer. Konsekvensene av det vil være for oss at enkelte expand/hide-bokser som vi har ikke blir markert som navigerbare.

Vi bruker per i dag en "inert polyfill" fra WICG (https://github.com/WICG/inert) som skal patche manglende inert muligheter. En feature i nettlesere som er enda til gode til å bli helt standardisert og landet i alle nettlesere. Dette blir brukt for å kunne ha elementer i DOM men ikke navigerbare for å enklere kunne gjøre transisjoner og bedre UU i mange tilfeller.

Denne buggen gjelder komponenter:

- Ui.TicketDetails
- Ui.Group
- Ui.Expandable

**Reprodusering**
1. Gå til Oversiktssiden
2. Aktiver voice over
3. Ekspander en billett
4. Prøv å naviger til detaljer
5. Får ikke navigert bort

**Forventet oppførsel**
Ved skjult burde det ikke være navigerbart. Når det er vist burde det være det. Ekstra viktig er dette for steder der skjema/inputs/radios blir brukt.

**Annen kontekst**

En alternativ måte å løse dette på er å fjerne/legge til DOM elementer hver gang. Da vil det ikke være mulig med f.eks animasjoner mellom tilstander uten andre sofistikerte løsninger (les: custom web component som brukes som en egen node via en dialog implementasjon eller lignende)

**Comment by gorandalum** [comment]
Fikk ikke reprodusert, prøvde med Safari både på OSX og iOS. Det ble fikset samme/tilsvarende bug på Expandable ved å bruke `Keyed`, men det er ikke gjort noen fiks på dette for TicketDetails (som brukes på oversiktssiden) og Group (som brukes i kjøpsprosessen).

Foreslår å lukke, om ikke du vil ta en rask test om du klarer å reprodusere @tormoseng?

**Comment by tormoseng** [comment]
@gorandalum Får ikke reprodusert det med VoiceOver på iOS/Safari.
