### ISSUE TITLE
[Bug] Kjøpsknapp og data fra billett forsvinner

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#319]
**Beskrivelse av bug**
Av og til når man logger inn i nettbutikken så forsvinner kjøpsknappen - både fra oversiktssiden og fra hovednavigasjonen i toppen.
Hvis man i tillegg har en billett fra før så forsvinner data om billetten, som reisende, sone og betalingsmiddel, billettype. 

Har blitt observert i både Chrome og Safari, med både helt nye og gamle brukerprofiler. Skjer ikke konsekvent. 

**Reprodusering**

Prøv å logg inn på bruker og se om knapper er borte eller ikke. 

**Forventet oppførsel**
- Kjøpsknapp tilgjengelig fra oversiktsside
- Kjøpsknapp tilgjengelig fra hovednavigasjon
- All data vises på eksisterende billett

**Screenshots**
![image (7)](https://user-images.githubusercontent.com/8980523/128134533-f6881d7c-8b79-4d18-b7dd-701e6cf4302c.png)
![image (8)](https://user-images.githubusercontent.com/8980523/128134538-388bd732-5f2d-41b6-8e20-9bf22f1b1725.png)
![Skjermbilde 2021-08-04 kl  08 42 44](https://user-images.githubusercontent.com/8980523/128134557-ec364bc5-7538-4cdc-8fb8-3ca172a2c9e4.png)

**Desktop (please complete the following information):**
 - Chrome, Safari, Firefox

**Comment by mjenssen** [comment]
Problemet er remote config, vi får ikke verdier derfra. Trolig relatert til dette: https://github.com/firebase/firebase-js-sdk/issues/5244

Ser vi får verdiene fra server (HTTP-kallet gir disse verdiene) men Firebase-SDKen gir oss tomme stringer tilbake.

En workaround er å hardkode disse inntil videre eller gå over til Firestore.

**Comment by mjenssen** [comment]
Firebase-teamet har fikset problemet på sin side. Har verifisert at jeg får data fra remote config i både Chrome, Safari og Firefox.
