### ISSUE TITLE
Gjøre det mulig å logge inn i Nettbutikken for kunder som er opprettet i Sørvis

### ISSUE THREAD

**Issue by vidtil** [AtB-AS/webshop#323]
Dersom man oppretter en ny kunde i Sørvis burde det være mulig for den aktuelle kunden å logge inn i nettbutikken. 

Dette er et aktuelt case ved betjening av kunder som møter opp fysisk hos Kundesenteret: Det er kanskje mest effektivt for kundesenteret å opprette kunden i Sørvis, og slike kunder burde likevel ha muligheten til å bruke nettbutikken etterpå. 

Pr starten av august håndteres dette ved at kundene som møter opp i kundesenteret får hjelp til å opprette profil selv i nettbutikken. Deretter selges billett i Sørvis f.eks. når en kunde skal betale kontant. Det må avklares om dette er en gangbar løsning på sikt.

**Comment by mjenssen** [comment]
Dette er en duplikat av #317
