### ISSUE TITLE
[Bug] Uventet oppførsel ved advarsel for overlappende periodebillett

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#328]
**Kontekst**
Denne observasjonen er fra staging, mens saken som er testet (#302) er prodsatt.

**Beskrivelse av bug**
Noen aspekter rundt advarsel om overlappende periodebillett (ref sak #302 ):
1. Hvis man har en periodebillett og forsøker å kjøpe en ny, så vises en advarsel (gitt samme tid og sone). Avbryt kjøpsprosessen, for deretter å starte "kjøp periodebillett" på nytt så vises ikke denne advarselen. Advarselen fremkommer kun første gang. Reload for å få den tilbake første gang man er inne i kjøp.
2. Hvis man kun har et klippekort liggende så fremkommer også advarsel ved kjøp av periodebillett. Ville trodd at man her ikke skulle fått advarsel, men siden klippekort har varighet i 1 år ser det ut til at denne også kommer med i sjekken.
3. Hvis man har f.ex en periodebillett for tid NÅ til tid NÅ+7dager for sone A-B1, så fremkommer advarsel riktig. Endres sonene til f.ex B2-B3 så blir ikke advarselen borte.

**Forventet oppførsel**
Sak #302 beskriver at advarsel skal fremkomme ved overlapp på både tid + sone. Implisitt så sier saken at det er kun ved periodebillett at advarselen skal gis - ikke om man har kun klippekort fra før. Samtidig skal advarsel fremkomme hver gang man går inn på "kjøp ny periodebillett" - ikke kun første gang

**Desktop**
 - OS: Mac OS
 - Browser Chrome og Safari

**Comment by mjenssen** [comment]
1. er enkelt å fikse - problemet er at avbryt resetter all state for butikk-siden og dette inkluderer de tidligere billettene du har.

Når det gjelder soner så er det vanskelig å finne ut hvilke soner som overlapper med andre soner. Vi har rett og slett ikke denne informasjonen lett tilgjengelig. Det går an å gjøre en sjekk på om sonevalget er _nøyaktig_ det samme som i en av billettene du allerede har, men det kan også bli feil. Derfor synes jeg det er greiest å bare gi en advarsel når man har en periodebillett i tiden du angir. Det er uansett kun "til informasjon".

Klippekort burde også håndteres spesielt, men usikker på om det er problematisk å ha den informasjonen.

**Comment by tormoseng** [comment]
@mjenssen Ser problematikken rundt sonene. Advarselen er såpass generisk - samtidig som den faktisk ikke hindrer nytt kjøp - så den er grei. Dette gjelder for så vidt også klippekort. For meg så virker det uproblematisk at advarselen står når jeg tenker meg om.

Da gjenstår kun pkt.1

**Comment by tormoseng** [comment]
Testet OK i staging
