### ISSUE TITLE
Advarsel om ugyldig starttidspunkt bør leses opp av skjermleser

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#330]
Hvis man på iOS med VoiceOver velger en dato før dagens dato så er det "Kunne ikke laste inn billettinformasjon. Prøv igjen" som leses opp. Her kunne jeg tenkt meg at det heller var meldingen "Starttidspunkt kan ikke være før nåværende tid og dato" som leses opp. Tilsvarende for tid > 90 dager frem i tid.

Evt at begge meldingene leses opp, men det er viktig at brukere av skjermleser får en tilbakemelding om den nye advarselen.

**Comment by gorandalum** [comment]
Gjort en endring i tilhørende PR for å forbedre dette. Endringen er at feil (røde bokser) får role="alert", mens advarsler får aria-live="polite". Det gjør at feil leses opp med en gang, mens advarslene leses opp når andre ting er ferdig lest opp.

**Comment by tormoseng** [comment]
Testet OK i staging
