### ISSUE TITLE
Tilrettelegge for kjøp av klippekort for reisende på metrobusstrekninger

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#343]
Vi må forberede for salg av klippekort for reisende som har mulighet til å starte reisen sin med validering på en holdeplassvalidator i en periode frem til MT kan lese klipperkort.

1) Legge til infomelding under billettkjøp klippekort
2) Fjerne sonevalg fra klippekortsbilletten.

Se skisseforslag: https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=1657%3A18204
![image](https://user-images.githubusercontent.com/50573205/129208088-f223c409-f9d5-477c-a552-a8a32d315722.png)

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).
- [ ] Fokusrekkefølge: tastaturrekkefølge og visuell rekkefølge er like, eller tastaturrekkefølge og visuell rekkefølge er ikke like, men det er mulig å forstå og bruke innhaldet
- [ ] Skjemaelementer, lenker, knapper eller iframes er koblet til en ledetekst i koden (f. eks aria-label og aria-labelledby)
- [ ] Skjemafelt skal ha ledetekster/instruksjoner
- [ ] Formål med lenker går tydelig fram av lenketeksten, eller lenketeksten og konteksten sammen
- [ ] Koden inneholder ikke syntaksfeil (ingen «fatal error» ved validering og ikke syntaksfeil)
- [ ] Innhold som kan betjenes med tastatur, får synleg fokusmarkering
- [ ] Skjemaelementer inneholder feilmeldinger stylet ihht. designsystem og feilmeldingene inneholder både informasjon om hva som er galt, hvor det har oppstått og forslag til retting.
- [ ] Nye sider skal ha sidetittel som er korrekt kodet og gir relevant beskrivelse av emne/formål med siden (f. eks: Kjøpshistorikk - AtB Nettbutikk og ikke bare «AtB Nettbutikk»)
- [ ] Det er mulig å navigere med tastatur gjennom alt innholdet på nettsiden, utan å bli stående fast i noen element.
- [ ] Tekst kan forstørres opp til minst 200 %-visning utan tap av innhold og funksjonalitet.
- [ ] Overskrifter, tabeller, overskriftsceller og lister er rett kodet.
- [ ] Bilder/illustrasjoner er kodet etter formål (ikke lenkede-dekorative bilder skaper ikke støy, mens bilder som er meningsbærende har tekstalternativ).

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-webshop).

**Comment by mjenssen** [comment]
Er det riktig å ha denne teksten i den "grønnblå" bakgrunnen? Ut i fra det vi har brukt hittil så skal info være turkis (sånn som er helt øverst) og advarsel/warning er gul. Føler dette burde være en advarsel med gul farge også sånn at folk kanskje faktisk leser den.

**Comment by mjenssen** [comment]
Her er de fire forskjellige tilstandene vi bruker:

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/23308/129308422-88219918-804a-4fa2-8746-ce5ce00c6a10.png">

Fra toppen: Info, Warning, Valid og Error.

**Comment by magnusolderoesaether** [comment]
Enig med deg Martin - vi kjører Warning

**Comment by magnusolderoesaether** [comment]
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/50573205/129341674-57a43b3a-f15d-47f3-976b-52029cc5f8f7.png">
