### ISSUE TITLE
[Feature] Lagre betalingskort for å forenkle fremtidige kjøp

### ISSUE THREAD

**Issue by gorandalum** [AtB-AS/webshop#344]
## Konseptuell beskrivelse og behov som skal løses
Brukerne skal få mulighet til å lagre et benyttet betalingskort for å enkelt kunne gjenbruke det senere, uten å måtte taste inn betalingsdetaljer på nytt.

## Løsningsforslag
Vi bruker Entur sin løsning, som er kalt "Recurring payment":
https://developer.entur.org/pages-sales-guides#use-recurring-payments

#### Funksjonelt
Ved kjøp i app, så må brukeren få presentert spørsmål om vedkommende vil lagre sitt betalingskort

#### Teknisk
Valget brukeren tar må styre parameteren `storePayment` i kallet for å opprette terminal url:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/createPaymentTerminal

#### Funksjonelt
Ved kjøp så bør lagrede betalingskort komme opp som mulige valg, sammen med Vipps, (nytt) Visa og (nytt) MasterCard 

#### Teknisk
Vi bruker Entur sitt recurring-payment API for å hente ut lagrede kort på brukeren:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/queryRecurringPayments

Hvis brukeren velger å bruke et av disse kortene så må man sende med det kortet som `recurringPaymentId` i kallet som oppretter transaksjonen:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/addTransaction

#### Funksjonelt
Under "Min Profil" skal brukeren få listet opp sine betalingskort, og mulighet for å slette de.

#### Teknisk
Vi bruker Entur sitt recurring-payment API for å hente ut lagrede kort på brukeren:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/queryRecurringPayments

Ved sletting bruker vi Entur sin delete recurring payment operasjon:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/endRecurringPayment

#### Funksjonelt
Brukeren får mulighet til å gi kallenavn til sine betalingskort, og mulighet for å markere et av betalingskortene som hovedkort.

#### Teknisk
Begge disse endringene gjøres med Entur sin update recurring payment operasjon:
https://petstore.swagger.io/?url=https://api.entur.io/api-docs/payment%3Fgroup%3Dpublic#/Payment%20API%20Public/updateRecurringPayment

## Andre kommentarer
- Entur har implementert denne flyten i sin app. Man kan ta en titt på den for inspirasjon.
- Jeg har et Postman-prosjekt liggende hvor det meste av denne flyten er implementert.

**Comment by tormoseng** [comment]
@gorandalum Her har jeg lagret 2 kort
![Screenshot 2021-08-31 at 09 14 38](https://user-images.githubusercontent.com/5812433/131459450-dfb0628d-1b47-43f5-a785-baeaaf06b7b3.png)

Men ser at utløpsdato blir 1 mnd etter hva jeg satte i betalingsvinduet. Satte 12/23 for VISA og 10/22 for MC.

**Comment by tormoseng** [comment]
Skulle gjerne hatt noe visuelt når man velger å betale med et lagret kort etter å ha trykket på "Gå til betaling". Denne knappen blir nedtonet, men ellers ingenting som skjer. Ikke en spinner eller melding om at betaling er i gang.

I tillegg er kanskje knappen "Gå til betaling" litt upresis da man ikke går noe sted med et lagret betalingskort sammenlignet med et nytt kort.

**Comment by tormoseng** [comment]
Får ikke til å fjerne et kort fra "Min Profil".
`Access to XMLHttpRequest at 'https://api.staging.mittatb.no/ticket/v2/recurring-payments/7235' from origin 'https://atb-webshop-staging.web.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by tormoseng** [comment]
Siste punkt om "Administrering av lagrede betalingskort" er ikke implementert, vel?

**Comment by gorandalum** [comment]
> @gorandalum Her har jeg lagret 2 kort
> Men ser at utløpsdato blir 1 mnd etter hva jeg satte i betalingsvinduet. Satte 12/23 for VISA og 10/22 for MC.

Good catch! Fra Entur får vi tilbake `2021-10-01T00:00:00Z`, men det skal altså ikke tolkes som 10/24.

**Comment by gorandalum** [comment]
> Skulle gjerne hatt noe visuelt når man velger å betale med et lagret kort etter å ha trykket på "Gå til betaling". Denne knappen blir nedtonet, men ellers ingenting som skjer. Ikke en spinner eller melding om at betaling er i gang.
> 
> I tillegg er kanskje knappen "Gå til betaling" litt upresis da man ikke går noe sted med et lagret betalingskort sammenlignet med et nytt kort.

Lagt til fiks for å få animasjon her:
https://github.com/AtB-AS/webshop/pull/362

Endring av tekst er kjapt gjort hvis man kommer på noe bedre.

**Comment by gorandalum** [comment]
> Får ikke til å fjerne et kort fra "Min Profil".
> `Access to XMLHttpRequest at 'https://api.staging.mittatb.no/ticket/v2/recurring-payments/7235' from origin 'https://atb-webshop-staging.web.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Skal være fikset nå.

**Comment by gorandalum** [comment]
> Siste punkt om "Administrering av lagrede betalingskort" er ikke implementert, vel?

Det stemmer.

**Comment by tormoseng** [comment]
> Endring av tekst er kjapt gjort hvis man kommer på noe bedre.

@magnusolderoesaether tar en titt på denne.

**Comment by tormoseng** [comment]
@gorandalum Har en auto-sjekk på a11y, og den vil gjerne ha inn alternativ tekst på bankkort-img (under summary periode/carnet + min profil). 

https://dequeuniversity.com/rules/axe/4.2/image-alt?application=axeAPI.

**Comment by tormoseng** [comment]
> Men ser at utløpsdato blir 1 mnd etter hva jeg satte i betalingsvinduet. Satte 12/23 for VISA og 10/22 for MC.
Re-testet OK

> Lagt til fiks for å få animasjon her:
Re-testet OK

**Comment by tormoseng** [comment]
> Har en auto-sjekk på a11y, og den vil gjerne ha inn alternativ tekst på bankkort-img (under summary periode/carnet + min profil).

@gorandalum Har du lagt til dette - eller hadde det vært like greit med aria-hidden her også?

**Comment by tormoseng** [comment]
Denne er nå testet ferdig og klar for Prod.
