### ISSUE TITLE
Endre t:kort format for anonymiserte tall

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#363]
I dag vises t:kort-nummersekvensen som [XXX XX60 8227223X]. Vi har fått tilbakemelding fra bruker på at dette er forvirrende siden den første sekvensen med 3X ikke gjenspeiler formateringen på det fysiske t:kortet som er 4X.
Foreslår at sekvensen vises slik, men bruk av asterisk i stedet for X som er vanligere ved anonymisering av kortnummer:

[**** **60 8227223*]

Kort oppsummert hva bug-en går ut på

**Reprodusering**

**Forventet oppførsel**
Hvordan burde det egentlig fungere?

**Screenshots**
Vis video eller skjermbilde av feil.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Annen kontekst**
Annen relevant informasjon

**Comment by gorandalum** [comment]
Ser dette greit ut?

![Screenshot 2021-08-31 at 14 03 57](https://user-images.githubusercontent.com/675421/131499341-a8a8a203-3c39-4c59-9877-a555d5977664.png)

Og er maskeringen av sikkerhetshensyn? For det er ikke akkurat vanskelig å finne ut nummeret når vi har feilmeldingen "t:kort id må starte på 1616 0060" ved inntasting av t:kortnummer.

**Comment by tormoseng** [comment]
Testet OK i staging.

Når det gjelder
> Og er maskeringen av sikkerhetshensyn? For det er ikke akkurat vanskelig å finne ut nummeret når vi har feilmeldingen "t:kort id må starte på 1616 0060" ved inntasting av t:kortnummer.

må jeg henvise til @magnusolderoesaether @hildeor

**Comment by tormoseng** [comment]
Avklart på møte at maskering er pga at disse feltene ikke lagres noe sted, men at de for brukeren representerer hvor mange tall de har fylt ut.

Sender saken videre.
