### ISSUE TITLE
[Bug] Får ikke til å legge til t:kort på Min profil i Firefox

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#369]
**Beskrivelse av bug**
Kort oppsummert hva bug-en går ut på

Kundeservice har mottatt flere henvendelser fra personer som bruker Firefox om at de ikke får registrert t:kort. Hvis de bytter til annen nettleser, f. eks Chrome så fungerer det.

@tormoseng Har testet følgende og **ikke** klart å reprodusere hittil:

Min profil:
- Firefox 89.0.2 / Windows i staging.
- Firefox 91.0.2 / Mac OS i prod.

Onboarding:
Fikk lagt til t:kort i staging i on-boarding med Firefox 91.0.2 / Mac OS

**Comment by gorandalum** [comment]
Vet vi noe mer? Hvilken feilmelding får de?

**Comment by hildeor** [comment]
Nei @tormoseng har prøvd å reprodusere men vi har ikke lykkes med det. Har bedt kundeservice om å innhente mer informasjon om det kommer flere henvendelser.

**Comment by toretefre** [comment]
Har forsøkt å reprodusere problemet i prod nå, både gjennom onboarding og å legge til på profilen i etterkant.

Fikk lagt til kort med: 
- Mac, Firefox 91.0.2
- Mac, Firefox 92.0
- Windows, Firefox 92.0
- Windows, Firefox 89.0
- WIndows, Firefox 89.0 med Adblock Plus
- Windows, Firefox 89.0 med uBlock Origin

Som en liten bug får jeg opp meldingen "Du har alt lagt til et t:kort" i en blå boks over onboardingskortet etter at jeg har tastet inn et gyldig t:kort-nummer og trykket videre. Meldingen dukker da opp i et halvt sekund før jeg blir videresendt til hovedsiden "Mine billetter". 

Kanskje det kan være relatert?

**Comment by hildeor** [comment]
Vi kan sikkert avvente denne til vi eventuelt hører mer fra kundeservice siden vi ikke klarer å reprodusere. Har heller ikle fått noen flere henvendelser fra kundeservice på det siden sist.

**Comment by tormoseng** [comment]
Lukker denne, og tar Firefox-delen videre i #390.
