### ISSUE TITLE
[Bug] SameSite cookie må inneholde Secure

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#372]
**Beskrivelse av bug**
I firefox får man beskjed om (i konsoll): "Some cookies are misusing the recommended “SameSite“ attribute"
og med videre spesifisering "Infokapsel «_ga_ZJNT7JRC05» vil snart bli avvist fordi den har «SameSite»-attributten satt til «None» eller en ugyldig verdi, uten «secure»-attributten. Les https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite for å lære mer om «SameSite»-attributten"

https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite spesifiserer at dersom SameSite er satt til None så må Secure være true. Ellers kan Lax benyttes som verdi. Usikker på implikasjonene her.

**Reprodusering**
1. Åpne opp konsoll i Firefox inne på nettbutikken
2. Se advarsel

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox
 - Version 91.0

**Comment by mjenssen** [comment]
Er dette i webshop eller Nets?

**Comment by tormoseng** [comment]
dette er inne på nettbutikken. Bare å la nettbutikken stå åpen med konsoll-debug

**Comment by mjenssen** [comment]
Hm, _ga er jo Google Analytics. Jeg får den vel ikke fordi GA blir sperra her 😅 Lurer på om dette er hos Google og ikke hos oss

**Comment by tormoseng** [comment]
Aha. Da er det jo bare å se bort i fra den da? Snedig at ikke Chrome rapporterer dette - men det er jo Google da... 🤷 🤔 😅

**Comment by mjenssen** [comment]
Ja, vi har noen kontroll over dette. Det er serveren til `www.googletagmanager.com` som er konfigurert feil. 🤷‍♀️ Jeg fant forøvrig denne her:

https://support.google.com/tagmanager/thread/18224991/samesite-warning-on-devtools-console?hl=en

Så visstnok skal dette bli et problem i Chrome også. Ut i fra diskusjonen i linken så burde dette vært fikset allerede i GTM samt også et problem i Chrome, men antar ting har blitt utsatt.

**Comment by tormoseng** [comment]
OK. Da lukker jeg denne saken.
