### ISSUE TITLE
[Bug] Håndtere fetch-kall i workbox

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#373]
**Beskrivelse av bug**
For hvert kall mot
GET https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel

så rapporterer Firefox i konsoll "Fetch-hendelseshåndterere må legges til under worker scriptets sin innledende evaluering. ./workbox-f7715658.js:1:749"

Usikker på hva konsekvensen er siden dette ikke oppstår i Chrome, men det har vært en del rapporter om feil i Firefox i det siste.

Ellers ser det også ut til at disse GET-kallene tar lang tid etter initiell lasting av nettbutikken. Ved å bare observere disse kallene så tar de opp mot 60 sek.

**Reprodusering**
1. Åpne opp konsoll i Firefox inne på nettbutikken
2. Se advarsel

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser Firefox
 - Version 91.0

**Comment by gorandalum** [comment]
Det kommer fra workbox, og de skylder igjen på en bug i Firefox
https://github.com/GoogleChrome/workbox/issues/2448

Som en workaround kan man bruke `inlineWorkboxRuntime: true`:
> You can set inlineWorkboxRuntime: true in your GenerateSW() config to cause all the service worker code to be included in a single output file, in which case the addEventListener() call should definitely be made as part of the initial service worker script evaluation.

Jeg er usikker på om dette får noen utilsiktede konsekvenser. Hva tror du @mjenssen?

**Comment by mjenssen** [comment]
Testet med og uten inline, og eneste jeg kan se er at du får 1 fil for service workeren i stedet for at det er 2 filer (`service-worker.js` og `workbox-<hash>.js`). Selve applikasjonen fungerer likt i begge tilfellene. Jeg fikk fortsatt den feilmeldingen en gang med inline, men det er mye sjeldnere enn uten inline. Vi bruker veldig lite av funksjonaliteten i Workbox, så jeg stemmer for at vi prøver dette.

Angående at requesten tar lang tid, så bruker denne requesten en teknikk som gjør at det kommer data fortløpende, men den resetter etter en gitt tid (vanligvis under et minutt). Det blir litt som å ha en WebSocket-connection men du har bare en-veis kommunikasjon. Siden det bare er en vanlig GET, så vil ikke browseren vise noe i response-taben før requesten resettes (altså: dette er kun et "problem" i developer tools).

**Comment by mikaelbr** [comment]
Not relevant new webshop
