### ISSUE TITLE
[Bug] UU for dårlig kontrast på advarselstekst på min profil

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#378]
**Beskrivelse av bug**
Advarselstekst som kommer opp f.ex ved fjerning av t:kort har for dårlig kontrast etter WCAG-standarden.

https://coolors.co/contrast-checker/a51140-000000

![Screenshot 2021-09-07 at 09 31 21](https://user-images.githubusercontent.com/5812433/132303468-5a6e5d93-4ea3-4adc-a463-3f69f78fa882.png)

**Comment by tormoseng** [comment]
@magnusolderoesaether Her må i tilfellet designet oppdateres s.a. kontrasten kommer over 4.5.

**Comment by hildeor** [comment]
![Feilmelding](https://user-images.githubusercontent.com/8980523/145964182-c0d587ea-3fbe-43d0-8050-7bf234ec2d11.png)

#A51140

**Comment by mikaelbr** [comment]
Not relevant new webshop
