### ISSUE TITLE
[Bug] Oppførsel på Firefox 92.0 med Windows 10

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#390]
Vi har tidligere hatt rapporter om at Firefox ikke fungerer tilfredsstillende for nettbutikken, men disse observasjonene har vi ikke klart å reprodusere. Se #369 

Etter nylig rapport fra intercom (https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/5173912/conversations/159245400044392) så ble det identifisert et problem med Windows 10 + Firefox 92.0. @rosvik har fått reprodusert dette problemet:

> Knappene er ikke skjult, men mangler HTML innhold. Fungerer i Chrome.
- Firefox:
![Screenshot 2021-09-27 at 08-08-49 AtB Nettbutikk](https://user-images.githubusercontent.com/5812433/134859218-aad45e6d-7836-4caa-9959-1260a3a442df.png)
- Firefox vs Chrome
![screen1](https://user-images.githubusercontent.com/5812433/134859228-2d6b1e7e-64c9-4654-ad17-8d0af611ba7e.png)

Her må vi se på hva det er som gjør oppførselen forskjellig, og det er nødvendig å ta en regresjonstest på kombinasjonen Firefox 92.0 og Windows 10 på øvrige funksjoner også.

**Comment by tormoseng** [comment]
For testing av kombinasjonen Firefox 92.0 + Windows 10. Har etterspurt muligheten til å benytte browserstack for testing, og avventer svar på om vi kan få en delt konto her.

**Comment by rosvik** [comment]
Ser at jeg også har samme problemet på Mac med Firefox Nightly (versjon 94.0a1), men ikke i "vanlig" Firefox 92.0. 

![Screenshot 2021-09-27 at 09 38 34](https://user-images.githubusercontent.com/1774972/134865007-babdea21-bc50-41d1-a934-24a2d31c41c5.png)

**Comment by hildeor** [comment]
Funker i Nightly her, så veldig rart. 
![Skjermbilde 2021-09-27 kl  09 56 00](https://user-images.githubusercontent.com/8980523/134867405-5af208f4-7e38-47eb-bc0a-184c7c690f10.png)
e

**Comment by mjenssen** [comment]
Dette høres ut som et problem med remote config. Kan vi verifisere at det kommer data derfra?

**Comment by rosvik** [comment]
![Screenshot 2021-10-05 at 10 50 18](https://user-images.githubusercontent.com/1774972/135991619-c89b52be-6e3e-4d8a-a799-191a5613dcda.png)

**Comment by rosvik** [comment]
Bare en oppdatering:

Jeg har fortsatt samme problemet i Firefox Nightly (nå versjon 96.0), men det fungerer fint i "vanlig" Firefox (nå versjon 94.0).

**Comment by tormoseng** [comment]
Ny bruker med samme problem: https://app.intercom.com/a/apps/vdemedo2/inbox/inbox/unassigned/conversations/159245400044978

Kan se ut til at det er Windows 10 med Firefox 94.0

**Comment by cbrevik** [comment]
Duplicate #369 ?

**Comment by tormoseng** [comment]
> Duplicate #369 ?

Lukket #369, men tar med testscenario på å legge til t:kort i denne saken.

**Comment by tormoseng** [comment]
Fikk ikke gjenskapt problemet på noen kombinasjoner av Windows/Mac og Firefox 94 eller 95beta (det er de versjonenene BS har).
![Screenshot 2021-11-23 at 13 55 57](https://user-images.githubusercontent.com/5812433/143029632-c2f25e23-9e24-4d6e-94e6-e48576713113.png)

**MEN** Så forsøkte jeg Windows 10 + Firefox 94 i privat vindu. DA fikk jeg gjenskapt problemet. Konsoll kaster (beklager dårlig bildekvalitet, men det er slik det ble):
![Screenshot 2021-11-23 at 14 05 57](https://user-images.githubusercontent.com/5812433/143029651-717deab6-6b56-4c78-8ade-fcfce7ad9840.png)

**Comment by gorandalum** [comment]
Blir løst av #437
