### ISSUE TITLE
[Bug] Webshop viser "Du har allerede en billett i dette tidsrommet" når det ikke finnes billetter på profilen

### ISSUE THREAD

**Issue by ingvisim** [AtB-AS/webshop#405]
På kjøp av periodebillett i webshop kommer det opp melding om "Du har allerede en billett i dette tidsrommet" til tross for at forsiden ikke viser noen billetter. På kontoen finnes det flere klippekort som har status som aktivert, og ikke utløper før om ca. et år i fremtiden. Disse klippekortene er tomme for klipp, og kommer derfor ikke opp på forsiden.
Konto-Id: ATB:CustomerAccount:0T942BlzJnM16O4iXKMvkGR64Q33 i staging

**Comment by gorandalum** [comment]
Slik det er i dag:
| Brukeren har | Har varslingstekst |
| --- | --- |
| Aktiv periodebillett med samme soner | ✅  | 
| Aktiv periodebillett med andre soner | ✅  | 
| Aktivt klippekort med samme soner og gjenstående klipp | ✅  | 
| Aktivt klippekort med samme soner og ingen gjenstående klipp | ✅  | 
| Aktivt klippekort med forskjellige soner og gjenstående klipp | ✅  | 
| Aktivt klippekort med forskjellige soner og ingen gjenstående klipp | ✅  | 

Rask løsning:
| Brukeren har | Har varslingstekst |
| --- | --- |
| Aktiv periodebillett med samme soner | ✅  | 
| Aktiv periodebillett med andre soner | ✅  | 
| Aktivt klippekort med samme soner og gjenstående klipp | ✅  | 
| Aktivt klippekort med samme soner og ingen gjenstående klipp | ❌  | 
| Aktivt klippekort med forskjellige soner og gjenstående klipp | ✅  | 
| Aktivt klippekort med forskjellige soner og ingen gjenstående klipp | ❌  | 

Mer omfattende løsning:
| Brukeren har | Har varslingstekst |
| --- | --- |
| Aktiv periodebillett med samme soner | ✅  | 
| Aktiv periodebillett med andre soner | ❌  | 
| Aktivt klippekort med samme soner og gjenstående klipp | ✅  | 
| Aktivt klippekort med samme soner og ingen gjenstående klipp | ❌  | 
| Aktivt klippekort med forskjellige soner og gjenstående klipp | ❌  | 
| Aktivt klippekort med forskjellige soner og ingen gjenstående klipp | ❌  |

**Comment by gorandalum** [comment]
Fikset med den raske løsningen. I test sjekk at tabellen under "Rask løsning" er gjeldende.

**Comment by tormoseng** [comment]
@gorandalum Hvis man har aktivt periodebillett så er det kun for ny periodebillett varslinga skal komme - eller skal den komme også ved kjøp av klippekort?

**Comment by gorandalum** [comment]
Det er kun periodebillett den ligger inne på, både før og etter denne endringen. Har ikke gjort noen ny vurdering rundt om det blir riktig eller ikke.

**Comment by tormoseng** [comment]
> Det er kun periodebillett den ligger inne på, både før og etter denne endringen. Har ikke gjort noen ny vurdering rundt om det blir riktig eller ikke.

Stemmer det! Takker.

**Comment by tormoseng** [comment]
Har sjekket det jeg kan sjekke. Ser bra ut. Vanskelig å sjekke aktivt klippekort med ingen gjenstående kjøp siden muligheten for å klippe seg ned er tatt bort. Finner heller ingen testbrukere som har klippet ned et klippekort uten å ha et klippekort med klipp igjen.
