### ISSUE TITLE
UU Legge på alt og role på ikon

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#406]
Etter merge av #392 så mangler AtB-ikon alternativ tekst og rolle for bruk til skjermlesere.

Dette elementet ligger nå som 

`<h1 class="pageHeader__logo"><a href="/"><img src="/images/icon-atb.svg">AtB Nettbutikk</a></h1>`

Etter diskusjon med @mikaelbr så bør følgende legges på img-tag: alt="" og role="none", siden selve bildet ikke gir noe ekstra mening når det ligger under tittelen "AtB Nettbutikk".

**Comment by gorandalum** [comment]
Ved bruk av VoiceOver så får man ikke til å manøvrere inn på bildet ved å flytte cursor, fokuset kommer bare på elementet som inneholder både bilde og overskrift, og da leses overskriften opp "heading level 1, link, atb nettbutikk". Når det er sagt så skader det ikke å legge inn, så jeg lager en PR på det.
