### ISSUE TITLE
[Bug] Visning av gyldighetsdato for UTC+2 tidspunkt i Firestore

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#423]
**Beskrivelse av bug**
Er det blitt noe rart med datohåndteringa når vi gikk over til vintertid? Denne billetten under har jeg hatt i staging lenge med en test som sjekker på at Gyldig fra er 11:50. Den vises nå som 10:50. En annen observasjon som støtter at det er noe rart er at kjøpstidspunktet er 11:50 - da kan ikke oppstartstidspunkt være 10:50…

Firestore sier `startDateTime: August 20, 2021 at 11:50:35 AM UTC+2`. Blir det feil med visningen når vi nå er på UTC+1?

![Screenshot 2021-11-18 at 13 32 59](https://user-images.githubusercontent.com/5812433/142421015-7223e306-16bb-4ec7-8a63-f525ddba28c5.png)

Et annet eksempel her, som viser forskjellen i visning via egen browser fra staging vs visning når det kjøres opp via GitHub (som har UTC sone). Legg merke til den ulike håndteringen av "Gyldig fra" og "Kjøpstidspunkt" i frontend.

![Screenshot 2021-11-18 at 13 46 02](https://user-images.githubusercontent.com/5812433/142421291-4d89e170-abf1-457e-afd2-81388b6a746a.png)

![Screenshot 2021-11-18 at 13 46 11](https://user-images.githubusercontent.com/5812433/142421314-7921962a-0478-446c-a519-2c65d2dec6a9.png)

**Reprodusering**
1. Logg inn på en testbruker som har billetter opprettet med UTC+2
2. Sjekk tidspunkt for Gyldig fra og til + Kjøpstidspunkt på "Mine Billetter"

**Desktop (please complete the following information):**
 - OS: OSX 11.5.2
 - Browser Chrome
 - Version 94.0

**Comment by cbrevik** [comment]
@jahnrohme lurer på om dette også er en feil i Sørivs? @tormoseng

**Comment by tormoseng** [comment]
@jahnrohme Det ser rett ut i Sørvis. 30-klipps-eksemplet fra over vises som gyldig fra 14:16 til 14:16, som er riktig siden tidssone er UTC+2 på aktuelle tidspunkter.

<img width="1352" alt="Screenshot 2021-11-22 at 12 44 27" src="https://user-images.githubusercontent.com/5812433/142856910-1c6d89c1-9a48-40af-ab58-24c7681d0ef6.png">

**Comment by tormoseng** [comment]
Denne er god
