### ISSUE TITLE
[Bug] Hopp over onboarding feiler med HTTP 500

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#424]
**Beskrivelse av bug**
Etter å ha opprettet en epostbruker, og bekreftet opprettelsen gjennom tilsendt epostlenke, så kommer man til onboarding. Hvis man her ikke ønsker å registrere navn og og kontakt-telefonnummer så kan man trykke "Hopp over". Gjør man dette uten å sette inn informasjon så får man HTTP 500 i respons på POST /register-kallet med responsen 
`upstreamError: "{\"errorCode\":400,\"shortNorwegian\":\"Ugyldig eller manglende parameter i tjenestekall\",\"longNorwegian\":\"Invalid value for MonthOfYear (valid values 1 - 12): -1\",\"shortEnglish\":\"Invalid or missing parameter in service call\",\"longEnglish\":\"Invalid value for MonthOfYear (valid values 1 - 12): -1\"}"`

Det som sendes inn av body i POST /register er
`{"firstName":"_","surname":"_","phone":"","email":null}`

For meg er det usikkert om det er email null som trigger feilen, men det kan videre diskuteres om den riktige løsningen vil være å fortsatt sende en POST /register med f.ex `{"firstName":"_","surname":"_","phone":"","email":"oppgitt-epost"}` (oppgitt-epost har man jo allerede) - eller å ikke sende en POST /register i det hele tatt siden bruker har valgt "Hopp over".

Hvis man derimot ikke ønsker å registrere navn eller telefonnummer, men trykker på "Neste" i stedet for "Hopp over" så er det en POST /register med body `{"firstName":"","surname":"","phone":"","email":"oppgitt-epost"}` som sendes. Denne er gull!

**Reprodusering**
1. Opprett en epostbruker
2. Bekreft tilsendt lenke
3. Trykk "Hopp over" på første onboardingssteg

**Screenshots**
![Screenshot 2021-11-22 at 09 38 59](https://user-images.githubusercontent.com/5812433/142830459-9a782672-cdc9-4ef3-8d7c-854119d6ad90.png)

**Desktop (please complete the following information):**
 - OS: Mac OSX 14
 - Browser Chrome
 - Version 94

**Comment by tormoseng** [comment]
Re-testet denne nå, og klarer ikke å reprodusere oppførselen. Veldig rart. Denne feilet konsekvent før helga.

**Comment by gorandalum** [comment]
Får ikke reprodusert

**Comment by tormoseng** [comment]
Det at det går kall og likevel registrerer telefonnummer (om dette er skrevet inn) hvis man velger "Hopp over" håndteres i https://github.com/AtB-AS/webshop/pull/432
