### ISSUE TITLE
[Feature] SCA-exemption for payment cards

### ISSUE THREAD

**Issue by cbrevik** [AtB-AS/webshop#442]
## Origin

- https://github.com/AtB-AS/team-platform/issues/17
- https://github.com/AtB-AS/atb-ticket/pull/104

Tilstøtende sak i app https://github.com/AtB-AS/mittatb-app/issues/1858

## Motivation

Enklere betalingsflyt for brukere, bankid-krav for lagret betalingskort er ikke mye bedre enn Vipps.

## Hypotheses and assumptions

- Flere brukere får bankid krav hver gang de betaler med betalingskort
- En flyt uten bankid for lave beløp vil oppleves som mye raskere enn andre alternativer

## Proposed solution

Test kort: https://shop.nets.eu/nb/web/partners/test-cards

- Sende inn `sca_excemption: true` i reserve-kall

## Acceptance Criteria

- [] Du får BankId-krav på test-kort som gir "challenge"
- [] Du får ikke BankId-krav på test-kort som ikke gir "challenge"

Ser ut som kanskje disse gir challenge:
![image](https://user-images.githubusercontent.com/4932625/144842328-359d9b4a-49e4-4a48-a6c8-5a9641d53902.png)

**Comment by gorandalum** [comment]
Ikke lenger nødvendig siden det blir fikset backend.

**Comment by cbrevik** [comment]
Tror en fortsatt må sende inn scaExcemption: true (for å enarmede SCA). Men det kan kanskje være en egen issue.

**Comment by cbrevik** [comment]
Må fortsatt sende inn den verdien fordi hvis vi enabler for alle så vil det brekke kjøp på gamle versjoner på app. Kan være at vi kunne skille på app og web

**Comment by mikaelbr** [comment]
Utvidet denne til å ha akseptansekriterier rundt teknisk endring på lagring av reservasjoner som nå er skrevet om til å fungere tilsvarende som på app for nettbutikk.

**Comment by tormoseng** [comment]
Denne er testet fint på staging + delvis på next.

@mikaelbr Testet dette på Next (https://atb-webshop-production--next-6spvs4ey.web.app/) og sjekket at /reserve ble sendt med _sca_excemption: true_. Testet 7-dagerskjøp (294 kr) med både MasterCard og Visa. Begge kom med verifisering (MC-verifisering og BankID). Er det noe annet som må på plass for at dette skal fungere på webshop (SCA virker til å fungere på App med dagens prod-backend).

**Comment by mikaelbr** [comment]
@gorandalum du som har jobbet med sca på app her. Det skal vel være løst utelukkende på backend her så så lenge `sca_excemption: true` blir sendt så skal det være OK (for du bekreftet at det ble sendt, @tormoseng ?)

**Comment by mikaelbr** [comment]
Det er jo bare jeg som var forvirret og fortsatte forvirringen med å lese feil hele tiden. Fix: https://github.com/AtB-AS/webshop/pull/496/files

**Comment by tormoseng** [comment]
Re-testet OK på next med:
- 7-dagerskjøp (294 kr) med MasterCard
- 7-dagerskjøp (294 kr) med Visa
- Klippekort barn (210 kr) med Visa
- Klippekort voksen (410 kr) med MasterCard
