### ISSUE TITLE
Kundenummer fra Sørvis vises i nettbutikken og app når man er logget inn

### ISSUE THREAD

**Issue by jahnrohme** [AtB-AS/webshop#469]
## Kontekst
Det er fortsatt en del noen brukere som har flere brukere i nettbutikken. F.eks at man oppretter bruker knyttet til både mobilnummer og e-post. Noen ganger vet ikke kunden selv hva som er hva, så kunden kontakter kundeservice for hjelp. For kundebehandlerne ville det blitt lettere for kundebehandleren og kunden å spørre om "kundenummer", slik at man kan på kortere tid finner ut at man snakker om den samme kundekontoen.

## Feature
Som en kundebehandler ønsker jeg at kundenummer vises i nettbutikken og appen når man er logget inn. Dette gjør det lettere for meg å identifisere riktig kunde-profil når vi skal assistere våre kunder ved spørsmål og support.

### Nettbutikk
![Overview](https://user-images.githubusercontent.com/8980523/152301039-33340d50-7388-4683-9cf3-aa6ee4c7fed1.png)
![Profile](https://user-images.githubusercontent.com/8980523/152301049-5ddc2f5d-a6aa-4a76-897b-19c2b3569b5a.png)

### App
![Logged in](https://user-images.githubusercontent.com/8980523/152301487-18bc2410-b1d4-4aed-a215-c54817f452da.png)

**Comment by cbrevik** [comment]
Krever spesifisering av @hildeor - hvor kundernummer skal vises.

Nummeret skal være tilgjengelig på modellen

**Comment by hildeor** [comment]
Oppdatert med skisser.

**Comment by jahnrohme** [comment]
Dette ser bra ut! :)

**Comment by mikaelbr** [comment]
FYI Tar denne mellom noen oppgaver her jeg.

**Comment by jahnrohme** [comment]
Konge! Takker :)

**Comment by mikaelbr** [comment]
Se #472 . Dette løser kun for webshop. Finner ikke kundenummer i app umiddelbart, så må høre med app-gjengen om den kan settes på claims. cc @cbrevik

**Comment by cbrevik** [comment]
Jess det er på claims, jeg bare fiksa det jeg: https://github.com/AtB-AS/mittatb-app/pull/2118

Som jeg lurer på PR-en der dog, er det forvirrende å vise kundenummer for anonyme brukere? De har kundenummer, siden de må ha det for å kunne gjennomføre et kjøp. Men gir det mening å vise det? Jeg synes på sett og vis det, siden det gjør det mulig for kundeservice å hjelpe de selv om de er anonym

**Comment by tormoseng** [comment]
@mikaelbr Selve vinsingen er fin i app og webshop. Oppdaterer seg ved innlogging/utlogging i app. På iOS/VoiceOver leses kundenummer opp fint, men på MacOS/Safari/Chrome + Android leses kundenummer opp som "tre millioner ...".

**Comment by mikaelbr** [comment]
Hmm. Dette er trolig også et problem med telefonnummer fra før? Jeg er ikke kjent med en automatisk løsning på dette. Det skal finnes noe skjermleser options i CSS men det er veldig lite støttet (tror det bare er støttet av Firefox). Alternativt må det staves ut manuelt i aria-tags, men finnes det ikke også noe screen reader innstillinger for dette? Må være et utbredt problem vil jeg tro 🤔

**Comment by tormoseng** [comment]
Ja, det er samme for telefonnummer (fire miliarder ...osv) + t:kort også. Rart vi ikke har sak på det.

Forslaget mitt er å legge ut dette i en egen sak for jeg mener visningen av kundenummer har såpass mye verdi i seg selv (sepesielt siden det er en issue fra før).

**Comment by tormoseng** [comment]
UU-sak lagt ut i egen issue #477 

Da er denne god!

**Comment by mikaelbr** [comment]
Se feil som en følge av dette: https://github.com/AtB-AS/webshop/pull/478

Påvirker også AtB, @tormoseng
