### ISSUE TITLE
Billettkjøp 2.0 - Kunne støtte flere billettprodukter i nettbutikk

### ISSUE THREAD

**Issue by hildeor** [AtB-AS/webshop#495]
## Konseptuell beskrivelse og behov som skal løses
Etter hvert som vi får inn flere billettprodukter i appen (nattbuss, hurtigbåt, ungdom, klippekort ...) så passer ikke dagens konsept for billettkjøp. De ulike billettproduktene har ulike kjøpsflyter og logikk og vi trenger et konsept som støtter denne og samtidig gir en god oversikt over de ulike produktene.
Det er også ønskelig å i større grad synliggjøre produktutvalget slik at det skal være lettere å vurdere for den enkelte hvilken type billett som passer ens behov. Dette muliggjør også en ny måte å fremheve produkter i perioder, eller å vise frem nye produkter.

- Som bruker ønsker jeg å få oversikt over produktutvalget slik at jeg kan velge det produktet som passer mine reisevaner
- Som bruker ønsker jeg å enkelt finne et spesifikt billettprodukt
- Som bruker ønsker jeg å enkelt kunne gjenta tidligere kjøp - da sparer jeg tid
- Som bruker ønsker jeg fleksibilitet til å kunne velge hvilken kanal jeg kjøper billetter gjennom (app, nettbutikk, sms osv)

## Hypotese og foreslått løsning

**Ny billettoversiktsside:**

<img width="719" alt="Skjermbilde 2022-04-12 kl  14 35 10" src="https://user-images.githubusercontent.com/8980523/162963519-a70aa302-f98d-4011-85e8-5e41064b10a0.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2858%3A41721)

**Periodebillett:**

<img width="640" alt="Skjermbilde 2022-04-12 kl  14 43 17" src="https://user-images.githubusercontent.com/8980523/162965102-6fb9909b-3b3a-45a4-b8ff-d226bc6149dc.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2862%3A44756)

**Klippekort:**

<img width="1355" alt="Skjermbilde 2022-04-12 kl  14 45 56" src="https://user-images.githubusercontent.com/8980523/162965375-28aef41d-dde0-45bf-a85d-91ff4d151946.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2975%3A47159)

**24-timers:**

<img width="688" alt="Skjermbilde 2022-04-12 kl  14 46 26" src="https://user-images.githubusercontent.com/8980523/162965458-3f9ff4bc-e944-48e3-9b73-902ba4ded18f.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2990%3A46136)

**Enkeltbillett:**

<img width="1102" alt="Skjermbilde 2022-04-12 kl  14 48 03" src="https://user-images.githubusercontent.com/8980523/162965746-9137e6c9-652b-4b34-8afa-aea388b6a2b1.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2990%3A46649)

**Ungdomsbillett:**

<img width="554" alt="Skjermbilde 2022-04-12 kl  14 48 33" src="https://user-images.githubusercontent.com/8980523/162965845-ce3430ea-e593-4133-8edc-368c5bbd9592.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2990%3A50474)

**Sommerpass:**

<img width="1285" alt="Skjermbilde 2022-04-12 kl  14 49 17" src="https://user-images.githubusercontent.com/8980523/162965971-0dc0460a-a5a5-474a-a2f9-87ef453b59cc.png">

[Lenke til Figma](https://www.figma.com/file/5fFAYrgt2I1mSYFVVcLVTp/Webshop-0.2?node-id=2990%3A50607)

**Annen nyttig kontekst**
Nevn annen nyttig informasjon og lenker som kan være viktig for denne oppgaven

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).
- [ ] Fokusrekkefølge: tastaturrekkefølge og visuell rekkefølge er like, eller tastaturrekkefølge og visuell rekkefølge er ikke like, men det er mulig å forstå og bruke innhaldet
- [ ] Skjemaelementer, lenker, knapper eller iframes er koblet til en ledetekst i koden (f. eks aria-label og aria-labelledby)
- [ ] Skjemafelt skal ha ledetekster/instruksjoner
- [ ] Formål med lenker går tydelig fram av lenketeksten, eller lenketeksten og konteksten sammen
- [ ] Koden inneholder ikke syntaksfeil (ingen «fatal error» ved validering og ikke syntaksfeil)
- [ ] Innhold som kan betjenes med tastatur, får synleg fokusmarkering
- [ ] Skjemaelementer inneholder feilmeldinger stylet ihht. designsystem og feilmeldingene inneholder både informasjon om hva som er galt, hvor det har oppstått og forslag til retting.
- [ ] Nye sider skal ha sidetittel som er korrekt kodet og gir relevant beskrivelse av emne/formål med siden (f. eks: Kjøpshistorikk - AtB Nettbutikk og ikke bare «AtB Nettbutikk»)
- [ ] Det er mulig å navigere med tastatur gjennom alt innholdet på nettsiden, utan å bli stående fast i noen element.
- [ ] Tekst kan forstørres opp til minst 200 %-visning utan tap av innhold og funksjonalitet.
- [ ] Overskrifter, tabeller, overskriftsceller og lister er rett kodet.
- [ ] Bilder/illustrasjoner er kodet etter formål (ikke lenkede-dekorative bilder skaper ikke støy, mens bilder som er meningsbærende har tekstalternativ).

Beskrivelse av QA prosessen finnes [her](https://github.com/AtB-AS/org/blob/master/guides/quality_assurance.md#qa-in-atb-webshop).

**Comment by gorandalum** [comment]
Lukker denne. Dette er en overordnet sak for billettering v2, og trackes av saken i leveranse-boardet:
https://github.com/AtB-AS/leveranser/issues/88

**Comment by Sebstorvik** [comment]
Lukker denne da det er en ny issue i ny repo.
