### ISSUE TITLE
Innlogging med e-post

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#51]
Opprettelse av brukere på vegne av andre krever en alternativ innlogging til mobiltelefon. Dette kan være en Google-e-post som settes opp på vegne av tredjepart, og brukes som registrering av AtB-profil. 

---

Det er foreløpig ikke mulig å endre innlogging eller merge innlogging. Dette gjøres i en andre oppgaver:

- https://github.com/AtB-AS/webshop/issues/239
- https://github.com/AtB-AS/webshop/issues/240

**Comment by havwig** [comment]
Første runde her bør implementeres som generell e-poststøtte. Det er godt støtta på backend, Firebase har alt vi trenger der. Det krever litt mer brukergrensesnitt, men vil være mye mer nyttig.

**Comment by mikaelbr** [comment]
Det er ikke alle konsepter og UI-mønster som er landet her.

Spørsmål som:
- Hvordan skal kontoer merges?
- Hvordan skal det informeres om flere kontoer i starten?
- Skal vi enforce merge ved å se på telefonnummer/epost?
- Hvordan skal vi endre epost og telefon?


Men jeg foreslår en fremgangsmåte som gjør at vi kan teknisk sett starte på dette samtidig som vi tar de avklaringene:

1. [ ] Legg opp til epost-innlogging som alternativ (i parallell, uten noe merging osv)
2. [ ] Legg til mulighet for å endre passord.
3. [ ] Legg til mulighet for å endre epost.
4. [ ] Legg til mulighet for å merge via profil-sidene
5. [ ] Legge til mulighet for å merge som en del av onboarding.

**Comment by mikaelbr** [comment]
Kan være en utfordring der du har registrert konto fra før via telefon og lagret en epost på den. Så registrerer du ny konto via epost og prøver onboarding og får beskjed om at den finnes fra før.

I dette tilfellet burde de få mulighet til å se noen siffer av telefonnummeret (2 siste?) slik at de kan logge inn med det telefon-nummeret og da merge de to kontoene.

**Comment by mikaelbr** [comment]
~~Hva skal vi kommuisere med denne? Måten du har logget inn på akkurat den gangen?~~

Edit: Funnet korrekt måte å liste ut alle providers som igjen kan brukes for å oppdatere/fjerne innloggingsmetode.

<img width="548" alt="Screenshot 2021-06-03 at 21 43 22" src="https://user-images.githubusercontent.com/606374/120702767-c1d43780-c4b4-11eb-960d-5449ac9a6002.png">

**Comment by mikaelbr** [comment]
Ting vi burde ta stilling til:

1. Skal vi enforce verifikasjon av epost? (mer kompleksitet/arbeid, men kan hjelpe til å unngå feil)
2. Skal vi ha oppdater passord i profil, eller bare sende reset-lenke?
3. Skal vi ha valg av innlogginsmetode upfront eller defaulte til telefon?

**Comment by mikaelbr** [comment]
Skal vi ha forskjellig "epost registrert" og innlogget epost?
Samme for telefon.

**Comment by mikaelbr** [comment]
- [x] Burde være Routing-basert navigasjon for innlogging slik at browser history kan brukes

**Comment by mikaelbr** [comment]
![Konsept Innlogging - Innloggingsflyt](https://user-images.githubusercontent.com/606374/120998657-94271100-c788-11eb-8b6d-82ec24f9fcf0.jpg)
![Konsept Innlogging - Profilflyt](https://user-images.githubusercontent.com/606374/120998723-a30dc380-c788-11eb-84d0-e625947f368a.jpg)

**Comment by mikaelbr** [comment]
For å kunne ha skikkelig verifikasjon eller oppdatering av epost for å holde Entur sine systemer og Firebase i sync burde det ligge en "konsolidertlag" i backend ved endring av epost eller telefon.

Dette er en utfordring vi møter senere med flere løsninger rundt App, reiseplanlegger web, osv. Så det burde løses som domenelogikk lag så nærme Entur/Firebase som mulig.

Foreslår derfor at vi deler inn i flere og prioriterer det viktigste som er alternativ til "på vegne av". Deler inn oppgaven i 2 steg: Innlogging og endring av epost/telefon. I første versjon nå (om 3 uker) sa har vi ikke støtte for endring av telefonnummer og epost. Om de vil endre så kan de gjøre det via kundeservice. Tror ikke det vil bety så mange folk i umiddelbar fremtid.

**Comment by magnusolderoesaether** [comment]
Denne flyten trenger et design. Hovedavklaring
1) Introdusere et ekstra steg med sidestilt valg mellom telefon eller e-post? 
2) Prompte telefoninnlogging. Hypotese: Enklest for flest. Understille valg for å logge inn med e-post.

Fordel: Kan måle hva brukerne velger. Enklere med tanke på å dytte skjermleserbruker til kompatibel innlogging.
Ulempe: Ekstra steg

@pettersuul og @hildeor jeg skal se litt på dette, men ønsker gjerne designforslag på hvordan flyten Mikael har smæsja opp funkjonelt kan struktureres optimalt. Hadde vært fint å få den ut tidlig etter markedsføringstiltakene over helga men ser det blir utordrende.  Jeg har limt inn flyten i Figma > Webshop 0.2 
![image](https://user-images.githubusercontent.com/50573205/121679066-3e1fd980-cab8-11eb-95a1-01f56ca2555b.png)

**Comment by magnusolderoesaether** [comment]
Forslag 
![image](https://user-images.githubusercontent.com/50573205/121851826-e7e8ab80-ccee-11eb-9654-491b23d5121f.png)

Ligger også forlagt til e-posttekster i Figmaen

**Comment by tormoseng** [comment]
@mikaelbr AtB-AS/webshop#248

**Comment by tormoseng** [comment]
Vil si at denne er testet OK i staging nå.

@mikaelbr Legger merke til at vi nå sender ut e-poster på engelsk - både ved verifisering og glemt passord. Har vi noen sak på å endre dette til norsk, og kanskje også gå gjennom teksten og evt få AtB-design?

**Comment by tormoseng** [comment]
> @mikaelbr Legger merke til at vi nå sender ut e-poster på engelsk - både ved verifisering og glemt passord. Har vi noen sak på å endre dette til norsk, og kanskje også gå gjennom teksten og evt få AtB-design?

Svar fra Mikeal er at dette er avhengig av hvilket språk OS har. Da lar vi den gå og flytter saken videre.
