### ISSUE TITLE
Informasjonssekvens om at billettkjøp er tilgjengelig i app

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#52]
Etter sekvens om å legge til t:kort under onbaording, vil bruker få informasjon om at ny reiseapp også kan brukes til billettkjøp, med lenker til App Store og Play Store

**Comment by pettersuul** [comment]
Noen forslag
![image](https://user-images.githubusercontent.com/56530785/116418174-2cea7880-a83c-11eb-99be-b6864d530a06.png)
![image](https://user-images.githubusercontent.com/56530785/116418331-54414580-a83c-11eb-8d8d-8a035d75bdc2.png)
![image](https://user-images.githubusercontent.com/56530785/116418365-5c998080-a83c-11eb-8c42-18a6bde73957.png)

**Comment by mikaelbr** [comment]
Her ble vi vel enig om første versjon. Dette løses vel av @mjenssen som en del av onboarding. Flytter til utviklingsboard og markerer som in progress.

**Comment by tormoseng** [comment]
Så fint ut for Chrome/Safari på Mac OS + Safari på iOS.
