### ISSUE TITLE
Refusjon av Fara-produkter

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#53]
Dette er et case som potensielt kan skape høy verdi for kundemigrering/brukeropplevelse ved overgang til ny nettbutikk, og samtidig avlaste Kundeserive med refusjonsrelaterte gjørejobber. Vi har behov for en grunnleggende hypotese på om dette er en go eller no-go til milepæl 3.

Dersom bruker under onboarding eller senere under "Min profil" ønsker å legge til et t:kort som er registrert hos Fara, vil hen få beskjed om dette og hvilke produkter som er aktive. Bruker kan velge om hen vil vente med å registrere kort til billettene er utløpt eller om hen vil utløse en refusjonsflyt.

CASE 1: Sending av t:kort-nummer utløser en spørring hos Fara og gir en respons på eventuelle aktive billetter: Hvilke? Gyldig hvor lenge?

CASE 2: Dersom spørring gir positivt svar (billetter funnet) får bruker velget mellom å vente med registrering av t:kort, eller sette i gang en refusjonsflyt.

**Comment by magnusolderoesaether** [comment]
Har lagt til en CASE 1 (light) og CASE 2 (full refusjon) på denne

**Comment by jahnrohme** [comment]
Håndtert, for øvrig er de fleste allerede refundert
