### ISSUE TITLE
Registering av t:kort etter opprettelse av AtB-profil

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#56]
Bruker som har valgt å hoppe over registrering av t:kort som en del av onboarding til opprettelse av profilen, kan enkelt se hvordan hen kan registrere et kort fra oversiktssiden, enkelt forstå hvilken informasjon som skal registreres, og få bekreftelse på at registrering er vellykket.

**Comment by mikaelbr** [comment]
Relatert: https://github.com/AtB-AS/webshop/issues/19

**Comment by mikaelbr** [comment]
Skal denne lukkes eller omformes til en slags "versjon2" greie?

**Comment by magnusolderoesaether** [comment]
Lukket med #19
