### ISSUE TITLE
Varsling når reiserett i er i ferd med å utløpe

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#58]
Brukere som har kjøpt periodebillett eller klippekort må kunne sette opp automatisk eller brukerdefinert varsling før et produkt utløper. Varsling kan gå til SMS og/eller e-postadresse. Vi kan også undersøke direkte "call-to-action" fra mottak av varsling til gjenkjøp/forlengelse av utgående billettype. Forslag automatisk rutine:

Klippekort: Når kun 2x klipp gjenstår
Periodebillett: x antall dager før utløpsdato

**Comment by magnusolderoesaether** [comment]
relatert til #62

**Comment by magnusolderoesaether** [comment]
Kan vi scope I to faser? Klippekort først, periode senere?

**Comment by mjenssen** [comment]
Siden klippekort ikke blir klart i prod til 28. juni, er det et poeng å bytte på disse fasene i så fall? Tidsbaserte produkter først (periodebillett, enkeltbillett, osv.) først, og så andre typer produkter (f.eks. klippekort).

**Comment by mikaelbr** [comment]
Splittes:

1. Periodiske kort
2. Klippekort (bruksbasert)

**Comment by mikaelbr** [comment]
Splittes:

1. Periodiske kort
2. Klippekort (bruksbasert)

**Comment by jahnrohme** [comment]
Denner er løst
