### ISSUE TITLE
Mulighet til å enkelt legge til et t:kort etter onbarding

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#59]
Brukere som ikke har laget til t:kort under onboardingen må enkelt finne en flyt for å registrere og bekrefte et nytt t:kort på sin profil.

**Comment by mikaelbr** [comment]
Dette jobber jeg med nå via oppgave https://github.com/AtB-AS/webshop/issues/19

**Comment by mikaelbr** [comment]
Kan se progresjon via https://github.com/AtB-AS/webshop/pull/55

**Comment by mikaelbr** [comment]
Stemmer vi closer denne i favør for #19

**Comment by mikaelbr** [comment]
Med mindre du tenker dette er en redesign av det som ligger inne. I såfall kan du gjenåpne @magnusolderoesaether . Men burde i såfall ta en sync på retning slik at vi unngår mye ekstraarbeid.
