### ISSUE TITLE
Kvalitetssikre og synkronisere begrepsbruk og copy på tvers av nettbutikk og app

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#61]
Vi må sikre at bruker opplever konsistent benevning og billettkonsepter og profilelementer på tvers av app og nettbutikk.

**Comment by monopoint** [comment]
I appen bruker vi ordlyden "Oppstart nå" om gyldighet for enkeltbillett. Det framstod for meg som litt fremmed, jeg hadde forventet "Gyldighet fra nå", eller "Gyldig med en gang", siden vi snakker om "gyldige" billetter ellers.
