### ISSUE TITLE
Tilby visuell støtte ved registrering av t:kort

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#71]
Vi må sikre at det blir enkelt for bruker å forstå hva det vil si å registrere et t:kort. Hvor finnes informasjonen? Hvilken informasjon skal jeg skrive inn? Hvordan vet jeg om jeg har gjort det riktig.

Skyss har animert et reisekort, og viser der hvor kortiID finnes, og hva bruker skal skrive inn hvor

**Comment by pettersuul** [comment]
![image](https://user-images.githubusercontent.com/56530785/116049994-442c3900-a677-11eb-9453-0755f40a2a8b.png)

**Comment by pettersuul** [comment]
Er dette beste måte for å hjelpe brukeren forstå f.eks. hvor man finner t:kort-nummeret?
Skal man legge inn hele nummeret? Kun 9 av 16 tall er nødvendig for å registrere kortet (`###### [_#########_] #`)

**Comment by mikaelbr** [comment]
Denne skal være løst for onboardingen nå, via #18.
