### ISSUE TITLE
Opprette en AtB-profil/logge inn med SMS

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#72]
Akseptansekriterier

- [ ] Enkelt forstå at SMS-kode brukes i samme inputfelt til enten opprettelse av profil eller innlogging på en eksisterende profil
- [ ] Automatisk i fokusfelt etter mottatt SMS-kode for innskriving av denne
- [ ] Lykkes i logge inn første gang/komme tilbake til allerede opprettet profil

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger om det ikke er mulig å logge inn.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by magnusolderoesaether** [comment]
Foreslår å endre teksten på knapp her fra "Logg inn" til "Logg inn / Opprett profil"
Det er den samme flyten som dekker to litt ulike brukermodus her

**Comment by magnusolderoesaether** [comment]
En liten bug her - ledeteksten droppes: 
![image](https://user-images.githubusercontent.com/50573205/115723499-5446ce80-a380-11eb-8669-dea294a7cf1e.png)

**Comment by mikaelbr** [comment]
Hele denne visningen må redesignes med nye komponenter for UU. Tenker vi må lande design i Figma for hva vi går for når vi først gjør den jobben.

**Comment by tormoseng** [comment]
Testet OK med både innlogging i ulike browsere og oppretting av konto.
