### ISSUE TITLE
Må oppfriske nettleser for at SMS-innlogging skal fungere etter utlogging

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#77]
**Beskrivelse av bug**
Etter en utlogging i nettbutikk klarer ikke siden å generere SMS-kode og blir stående å spinne. Etter oppfrisking av nettleser fungerer det. 

**Reprodusering**
1. Logg ut av nettbutikk

**Forventet oppførsel**
Hvordan burde det egentlig fungere?

**Screenshots**
Vis video eller skjermbilde av feil.

**Desktop (please complete the following information):**
 - OS: Catalina 10.15.7
 - Browser Safari

**Smartphone (please complete the following information):**

**Annen kontekst**
Annen relevant informasjon

**Comment by mjenssen** [comment]
Dette er relatert til ReCaptcha. Komponenten bør trolig resettes.

**Comment by tormoseng** [comment]
Testet OK. Oppførsel som forventet.
