### ISSUE TITLE
[Feature] Gi tilbakemeldinger til utviklingsteam om feil og forbedringer

### ISSUE THREAD

**Issue by magnusolderoesaether** [AtB-AS/webshop#79]
Innlogget i nettbutikken tilbys bruker en mulighet til å gi AMP direkte tilbakemeldinger på feil, mangler eller forbedringsforslag i nettbutikken. Dette vil være et viktig bidrag til brukermedvirkning og forbedring av opplevelsen. 
Vi ønsker å gjenbruke Intercom til dette.
---

## Akseptansekriterier

- [ ] Enkelt å finne tilbakemeldingsfunksjon og forstå hvilken type tilbakemeldinger dette gjelder
- [ ] Bruker kan registrere en tilbakemelding ved hjelp av tekst og/eller bilder og sende
- [ ] AMP mottar tilbakemelding i Intercom
- [ ] Bruker kan se status på chaticon når AMP har svart på henvendelse
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Sjekket prisingen til Intercom og det ser ut til at det ikke er noen ekstra kostnader med å bruke flere klienter på ulike plattformer.

**Comment by tormoseng** [comment]
Testet OK på desktop og mobil

**Comment by tormoseng** [comment]
Som testet i nettbutikken så får bruker et valg om å legge inn epost for å bli varslet ved svar. Dette fungerte ikke helt. Avklares på slack og blir evt en ny sak.
