### ISSUE TITLE
Make components based on current code

### ISSUE THREAD

**Issue by mjenssen** [AtB-AS/webshop#8]
UI elements are either just part of the page or standalone functions inside each page module. This code should be changed to more standalone elements/fragments/components that can be used everywhere in the app.

- Prefer builder pattern for components with many properties
- Prefer keeping state outside of component if possible
- Prefer one module per component
- Prefer styles/variants instead of multiple components that mostly do the same thing

**Comment by mikaelbr** [comment]
Kan denne lukkes til fordel for å bake de inn i oppgavene fremover?
