### ISSUE TITLE
[Feature] Rediger samtykker under kontosiden.

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#81]
- [ ] Update account page to new design for showing and editing consents

**Konseptuell beskrivelse og behov som skal løses**
Brukere skal kunne oppdatere samtykke, trekke de tilbake eller legge til nye underveise i kontoen sin. 

**Hypotese og foreslått løsning**

<img width="588" alt="Screenshot 2021-05-11 at 09 10 16" src="https://user-images.githubusercontent.com/606374/117773533-b6d11300-b238-11eb-9dda-31d696909002.png">

**Annen nyttig kontekst**
Samtykker lagres i Entur og er samme datagrunnlag som i onboarding.

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by pettersuul** [comment]
![Screenshot 2021-05-05 at 15 16 29](https://user-images.githubusercontent.com/56530785/117146890-f5884880-adb4-11eb-9fdf-f49738aacb50.png)

**Comment by mikaelbr** [comment]
Når man trykker på boksene vil det automatisk lagres endringer.

**Comment by tormoseng** [comment]
Husk å legge til setningen "Samtykker kan du endre på når som helst" i onboardingen for samtykker når denne saken er klar. Ref #17

**Comment by tormoseng** [comment]
Testet OK i staging. Prøvd med Chrome/Firefox på MacOS + VoiceOver på Chrome/MacOS + VoiceOver på Safari/Chrome/iOS + TalkBack på Chrome/Android.

Sjekket også feilmld om epost ikke er registrert + om /consent-kall feiler.
