### ISSUE TITLE
[Feature] Legg til mulighet for å redigere navn/etternavn i profil

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#83]
**Konseptuell beskrivelse og behov som skal løses**
For de som hopper over onboarding burde det være mulig å legge til navn i ettertid.

**Hypotese og foreslått løsning**

![Screenshot 2021-04-28 at 13 24 39](https://user-images.githubusercontent.com/606374/116395989-18e74c80-a825-11eb-83ed-74a3eb90564d.png)

![Screenshot 2021-05-19 at 10 23 00](https://user-images.githubusercontent.com/606374/118780321-363f9180-b88c-11eb-9313-9fe03e7d6174.png)

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by mikaelbr** [comment]
Fra design sync: Ved feilmelding ved lagring gi notifications.

**Comment by tormoseng** [comment]
Fungerer fint i div nettlesere på Mac og iOS
