### ISSUE TITLE
[Feature] Vis oversiktsside med melding ved vellykket kjøp.

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#85]
**Konseptuell beskrivelse og behov som skal løses**
Se https://github.com/AtB-AS/webshop/issues/63 for kontekst.

Etter endt kjøp burde bruker se konsekvensene av kjøpet med å gå til visning der kjøpet listes ut. Som en bekreftelse burde vi også vise melding om kjøpt billett. Og feilmeldinger som kan skje både med NETS og Vipps.

**Hypotese og foreslått løsning**

- "Notification" for feil/vellykket melding.
- Vis kjøpt billett med en liten animasjon inn?

---

## Akseptansekriterier

- [ ] Fungerer med tastaturnavigasjon
- [ ] Bruker rette farger og størrelser iht. design system
- [ ] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [ ] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).
- [ ] Håndterer feil fra NETS (avbrudd, mangel på penger, etc)
- [ ] Håndterer feil fra Vipps (avbrudd, mangel på penger, etc)
- [ ] Sendt til oversikten ved vellykket kjøp via NETS og Vipps.
- [ ] Er tydelig nok at det er kommet inn en ny ordre i oversikten.

**Comment by mikaelbr** [comment]
Løser noe ved #108 , men det krever større omskriving for å løse alt på en god måte. Det viktigste her nå er bare at ved Vipps så sendes man ikke til en rar API-side som ingen skjønner noe av. Så må det gjøres noen generelle løft på feilhåndtering, forhold mellom vår løsning og bruk av Vipps/Nets osv. Se #107 for kontekst og arvtager for mer brukervennlig og robust integrasjon med betalingsløsninger

**Comment by tormoseng** [comment]
@mikaelbr "Er tydelig nok at det er kommet inn en ny ordre i oversikten." For NETS er dette greit da man sendes tilbake til nettbutikken og ser notifikasjonen om ny billett. Ikke like greit med Vipps hvis man er litt treg med å lukke vinduet. Da er notifikasjonen borte. Men tenker uansett at dette er greit nå pga #107 og siden vanlige brukere neppe vil ha like mange aktive billetter som min testbruker :-)

**Comment by mikaelbr** [comment]
Jeg syns ikke det er tydelig nok nei 😛  . Derfor jeg mener #107 må på plass. Men jeg tror vi ikke får det gjort innen pilot 2 så vi må prioritere litt.

**Comment by tormoseng** [comment]
Testet OK i staging. Håndterer fint avbryt fra NETS/Vipps. Videre håndtering tas i #107.
