### ISSUE TITLE
[Bug] Får kjøpt billett på eksisterende sesjon etter at brukeren er fjernet fra firebase

### ISSUE THREAD

**Issue by tormoseng** [AtB-AS/webshop#88]
**Beskrivelse av bug**
For min bruker fikk jeg beskjed i Chrome om at jeg hadde for mange innlogginger (ingen var mislykkede selv om tekst i grensesnittet sa "...for mange ganger uten hell...". Mikael fikk slettet brukeren fra staging. 

Oppdaget da at jeg hadde allerede en etablert sesjon med samme bruker på Edge. Med denne sesjonen fikk jeg gjennomført et billettkjøp (ref 77QUYMD2), og manøvrert gjennom gyldige billetter og kjøpshistorikk.

**Reprodusering**
1. Logg inn i to ulike browsere
2. Logg inn for mange ganger i en av de
3. Fortsett i den andre browseren med bl.a. billettkjøp

**Forventet oppførsel**
Hvordan burde det egentlig fungere?

**Desktop (please complete the following information):**
 - Mac OS 11.2.3
 - Chrome 90.0.4430.93 og Edge 90.0.818.49

**Annen kontekst**
Fra Slack-tråd: https://mittatb.slack.com/archives/C01MT34KJ4B/p1619695510319000
- Mikael: Det er jo egentlig ikke noe som kommer til å skje men det kan skje f.eks at profilen blir deaktivert
- Martin: Vi må sikkert gå litt i dybden her når vi skal se på sletting av konto (initiert av kunden). Det ser ut som profilen som ligger hos Entur har all informasjon fortsatt. Vet det var snakk om at vi slettet for mye hos Entur og fikk beskjed om å ikke gjøre det, men noe vi må se nærmere på.

**Comment by tormoseng** [comment]
Ekstrainfo. Over natta kan jeg igjen opprette en bruker på samme mobilnummer som ble sletta i staging. Men det henger tydligvis igjen info et sted siden jeg får beskjed om at oppgitt epost-adresse allerede finnes (på den sletta brukeren), og at oppgitt t:kort er koblet til en eksisterende konto (på den sletta brukeren).
<img width="367" alt="Screenshot 2021-04-30 at 09 01 21" src="https://user-images.githubusercontent.com/5812433/116660503-6a154e80-a993-11eb-85c7-a0873c478665.png">
<img width="569" alt="Screenshot 2021-04-30 at 09 03 01" src="https://user-images.githubusercontent.com/5812433/116660530-74374d00-a993-11eb-94d7-ca94b2e7a134.png">

**Comment by mikaelbr** [comment]
@tormoseng check if this is still a problem on new webshop

**Comment by mikaelbr** [comment]
Close if not

**Comment by tormoseng** [comment]
Cannot reproduce this one, so I'll keep it closed.
