### ISSUE TITLE
[Feature] Legg til datagrunnlag for å si om bruker har andre billettbærere

### ISSUE THREAD

**Issue by mikaelbr** [AtB-AS/webshop#90]
**Konseptuell beskrivelse og behov som skal løses**
Nettbutikken burde vite om bruker har billettbærer via annen mobil og da travelcard. En ting er å velge billettbærere, men også for å gi informasjon til sluttbruker at mobil er en ting.

Se eksempelbilde:

<img width="336" alt="Screenshot 2021-04-29 at 15 25 51" src="https://user-images.githubusercontent.com/606374/116557903-30930380-a8ff-11eb-844c-cefe764dab46.png">

For at dette skal være mulig så trenger vi datagrunnlag på profilen for å si om brukeren har logget inn via app eller ikke.

Alternativt kan vi unngå denne formuleringen og heller formulere det som at du kan laste ned mobil når som helst og bruke den som billettbærer.

**Comment by jahnrohme** [comment]
duplicate: token toggle
