### ISSUE TITLE
[Feature] Header og navigasjon

### ISSUE THREAD

**Issue by pettersuul** [AtB-AS/webshop#93]
**Konseptuell beskrivelse og behov som skal løses**
Grunnleggende navigasjon i nettbutikken.

**Hypotese og foreslått løsning**
Klassisk header med logo og tittel i høyre hjørne.
Når man er logget inn vises navigasjonen:
- Ny periodebillett (snarvei til kjøpsprosess, disablet hvis man ikke har gyldig billettbærer)
- Kjøpshistorikk
- Min profil
- Logg ut (plasseres i høyre hjørne)

![image](https://user-images.githubusercontent.com/56530785/116560946-245c7580-a902-11eb-927b-96b619adbfca.png)
![image](https://user-images.githubusercontent.com/56530785/116560956-27576600-a902-11eb-9eea-3d1e50d1fafe.png)

**Annen nyttig kontekst**
Nevn annen nyttig informasjon og lenker som kan være viktig for denne oppgaven

---

## Akseptansekriterier

- [x] Fungerer med tastaturnavigasjon
- [x] Bruker rette farger og størrelser iht. design system
- [x] Gir feilmeldinger på komponentnivå eller som global melding til siden.
- [x] Fungerer i alle store evergreen nettlesere.
- [ ] Fungerer i alle størrelser og flater (mobil, desktop, etc).

**Comment by tormoseng** [comment]
Fungerer ikke helt på mobil. Se kommentar på #82 med skjermbilde.
